### ISSUE TITLE
Error running on Remote Host

### ISSUE THREAD

**Issue by tyler274** [microsoft/vscode-makefile-tools#216] opened 2021-09-30 20:53 UTC
Getting this error trying to run on an Ubuntu Stable 20.4 remote host. "-g" is on for every compiler invocation.
0.2.2 extension version
1.60.2 VSCode version
```
Unable to open 'raise.c': Unable to read file 'vscode-remote://ssh-remote+HOSTNAME/build/glibc-ZN95T4/glibc-2.31/sysdeps/unix/sysv/linux/raise.c' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+HOSTNAME/build/glibc-ZN95T4/glibc-2.31/sysdeps/unix/sysv/linux/raise.c').

**Comment by andreeis** [comment] 2021-09-30 23:15
@tyler274, thank you for opening this report.
This could be a duplicate of https://github.com/microsoft/vscode-makefile-tools/issues/213, which is very likely to be a bug in the CppTools extension, and not Makefile Tools.

@WardenGnaw, can you confirm if this issue and 213 are related to https://github.com/microsoft/vscode-cpptools/issues/2762?

**Comment by WardenGnaw** [comment] 2021-09-30 23:17
Yes. Unless you have the glibc source for `raise.c`, it prompts this message indicating you are trying to stop in a frame where there is no matching source code.

**Comment by bobbrow** [comment] 2021-09-30 23:22
@WardenGnaw Supposing the developer has the glibc source and the URI looks like the one above (`vscode-remote://`).  Would cpptools be able to load it?

**Comment by WardenGnaw** [comment] 2021-10-01 00:00
If they had exactly `/build/glibc-ZN95T4/glibc-2.31/sysdeps/unix/sysv/linux/raise.c` on the machine, yes. IIRC VS Code converts `vscode-remote://ssh-remote+HOSTNAME/` when we give them a file path with that prefix.

**Comment by gcampbell-msft** [comment] 2023-10-23 14:22
@tyler274 Since this was confirmed so to be an issue on the vscode-cpptools extension, in combination with the age of this ticket, I am closing this ticket. If the issue still persists, please create an issue [here](https://github.com/microsoft/vscode-cpptools/issues)

**Closed by gcampbell-msft** 2023-10-23 14:22 UTC
