### ISSUE TITLE
Compiling with multiple jobs corrupts the problem view

### ISSUE THREAD

**Issue by KrestenHelstrup** [microsoft/vscode-makefile-tools#421] opened 2023-02-20 08:31 UTC
Hi,
When I run make with multiple jobs (-Jx) parameter the problem view gets corrupted. The file path get mixed with compiler arguements, so whenever I click on a problem I get the error "file not found".

Running windows, make, arm-none-eabi-gcc.

**Comment by andreeis** [comment] 2023-03-09 09:38
@KrestenHelstrup, if the build output of "make" itself is interleaved and mingled because of the parallelism I would be tempted to say is by design. While we still research this and try to repro on our side... please share for us how you define your "makefile.*" settings in your .vscode/settings.json, the output of the "make" build (text) and a screenshot with how the problems view looks like.

**Comment by KrestenHelstrup** [comment] 2023-03-19 15:36
@andreeis, indeed the output from make itself is interleaved due to multiple jobs running. After investigating more I believe this is a feature of make that can be resolved with the -O option (https://www.gnu.org/software/make/manual/html_node/Parallel-Output.html). I guess we have to update to make => 4 to resolve the issue on our side.

**Comment by andreeis** [comment] 2023-03-21 17:45
@KrestenHelstrup , perfect. Then I am closing this issue and if you encounter anything else open a new one or reopen this if in the end even -O won't help with the problems tab being clean.

**Closed by andreeis** 2023-03-21 17:45 UTC
Labels: bug, more info needed
