### ISSUE TITLE
The "#define"  information in the Makefile will be recognized as unrecognized token

### ISSUE THREAD

**Issue by Ivanbeethoven** [microsoft/vscode-makefile-tools#526] opened 2023-11-13 07:41 UTC
This example comes from AFL: https://github.com/google/AFL

This "#define" does not exist in the C code, but is passed in through the compiler command in the Makefile file. 
An error is still reported after being recognized by the makefile.
It seems that define was indeed recognized and expanded, but an error occurred

![image](https://github.com/microsoft/vscode-makefile-tools/assets/65935895/94be3118-de60-49b6-83cb-5d040750facf)

Here is my `.vscode/c_cpp_properties.json`: 
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}
```
I have temporarily made the following modifications to alleviate this error:

```json
{
      "configurations": [
        {
          "name": "Linux",
          "includePath": [
            "${workspaceFolder}/**"
          ],
          "defines": [],
          "compilerPath": "/usr/bin/gcc",
          "cStandard": "c99",
          "intelliSenseMode": "linux-gcc-x64",
          "compilerArgs": [
              "-O3",
              "-funroll-loops",
              "-Wall",
              "-D_FORTIFY_SOURCE=2",
              "-g",
              "-Wno-pointer-sign",
              "-DAFL_PATH=\"$(HELPER_PATH)\"",
              "-DDOC_PATH=\"$(DOC_PATH)\"",
              "-DBIN_PATH=\"$(BIN_PATH)\""
            ]
          }
      ],
      "version": 4
}
```

**Comment by gcampbell-msft** [comment] 2023-11-17 18:00
@Ivanbeethoven Thank you for bringing this to our attention and pointing us to the project that it's happening in!

Since there is a reasonable workaround, this might not get fixed immediately (in the next release), but we will definitely put it on the backlog to investigate a fix for an upcoming release. Thanks!

**Comment by snehara99** [comment] 2024-10-16 19:27
I believe this has to do with: https://github.com/microsoft/vscode-makefile-tools/issues/465 and https://github.com/microsoft/vscode-makefile-tools/issues/497

**Comment by snehara99** [comment] 2024-10-16 20:04
@Ivanbeethoven another temporary workaround that I tested and works is to use...
`-D 'DOC_PATH="$(DOC_PATH)"'` 
...instead of...
`-DDOC_PATH=\"$(DOC_PATH)\"` 
...in your Makefile. The issue stems from escaping the double quotes.

**Comment by snehara99** [comment] 2024-12-16 14:27
@Ivanbeethoven The fix for this should be available on the latest pre-release version of Makefile Tools, so we will mark this as closed. Please feel free to open another issue if this ends up reproducing.

**Closed by snehara99** 2024-12-16 14:27 UTC
Labels: bug, Feature: accuracy
