### ISSUE TITLE
Apostrophes are added to make command when pressing build

### ISSUE THREAD

**Issue by creekdrop** [microsoft/vscode-makefile-tools#275] opened 2022-02-05 16:25 UTC
Extension suddenly stopped working. I noticed that it adds apostrophes when running make command. I get the following error:
```
At line:1 char:12
+ 'make.exe' 'all'
+            ~~~~~
Unexpected token ''all'' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```
I can run make all via terminal successfully, however build as well as build clean buttons of the extension does not work. Same error I get if I type 'make' 'all' with apostrophes.

**Comment by hagaigold** [comment] 2022-02-05 23:25
Something broke with the last update of VS Code (1.64.0):
```
> Executing task: 'make.exe' 'clean' <

''make.exe'' is not recognized as an internal or external command,
operable program or batch file.
The terminal process "C:\WINDOWS\System32\cmd.exe /d /c 'make.exe' 'clean'" terminated with exit code: 1
```

When I downgrade back to 1.63.2, the extension is working:
```
> Executing task: ""make.exe" "clean"" <

rm -rf *.o

Terminal will be reused by tasks, press any key to close it.
```

**Comment by creekdrop** [comment] 2022-02-10 20:45
VS Code update 1.64.2 seems to solve the issue.

**Comment by andreeis** [comment] 2022-02-14 22:06
@creekdrop and @hagaigold, thank you for investigating this problem and for finding the root cause. Since it was fixed in VSCode, I am closing this issue and let us know if you encounter any other problem going forward.

**Closed by andreeis** 2022-02-14 22:06 UTC
