### ISSUE TITLE
DEBUG button ignores MIMode and miDebuggerPath settings in launch.json

### ISSUE THREAD

**Issue by fischerjd** [microsoft/vscode-makefile-tools#240] opened 2021-11-27 07:17 UTC
I'm using vscode v1.62.3 on a Fedora 34 host w/ the KDE/Plasma spin.

I'm following along with Julia Reid's YouTube video [Makefile Support in Visual Studio Code with Julia Reid](https://youtu.be/cEC2iZCS2Lk?t=631) (except that I am not using the SSH extention), and at around the 10:30 mark she clicks on the **DEBUG** button to begin a debugging session.

When I click on the **DEBUG** button, I get an error message dialog that says

>Unable to start debugging. The value of miDebuggerPath is invalid

<hr />

ISSUE #1)  The error message dialog has a button on it labeled **Open 'launch.json'**, but this seems to be the wrong configuration file with which to manage this problem.  After some experimentation I've discovered that (on my system) the configuration settings **MIMode** and **miDebuggerPath** belong in file **settings.json** and not in **launch.json**.

<hr />

ISSUE #2)  If I want to invoke a debugging session via the MAKEFILE extension's **Debug** button, the configuration settings **MIMode** and **miDebuggerPath** must be defined in **settings.json**, i.e., both settings are required; they are not optional:

```
{
    "makefile.extensionOutputFolder": "./.vscode",
    "makefile.launchConfigurations": [
        {
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin",
            "cwd": "/home/me/tmp",
            "binaryPath": "/home/me/tmp/demo",
            "binaryArgs": []
        }
    ]
}
```

In **settings.json**, if I define **MIMode** and omit (or comment out) **miDebuggerPath**, then when I click on the MAKEFILE extension's **DEBUG** button the extension fails to find the debugger program **gdb** and I get the aforementioned error dialog that says

>Unable to start debugging. The value of miDebuggerPath is invalid

In **settings.json**, if I define **miDebuggerPath** and omit (or comment out) **MIMode**, then when I click on the MAKEFILE extension's **DEBUG** button the extension emits the following error messages to the **Terminal** window:

```
error: unknown option: --interpreter=mi
error: unknown option: --tty=/dev/pts/7
Use 'lldb --help' for a complete list of options.
```

<hr />

FWIW, on this host,

```
$ which gdb
/usr/bin/gdb
```

and folder ```/usr/bin``` is in my $PATH environment variable:

```
$ echo $PATH
/home/me/.local/bin:/home/me/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
```

<hr />

FWIW2, if I remove or comment out the settings for **MIMode** and **miDebuggerPath** in files **settings.json** and **launch.json**, I can successfully invoke a GDB debugging session by opening VS Code's **File** menu and selecting the option **Start Debugging (F5)**, or by pressing the **F5** function key.  (NB: The output I see on the **DEBUG CONSOLE** indicates VS Code is invoking GNU gdb when I press the F5 key; it is not invoking lldb.)  (NB: The lldb debugger package is also installed on this host.)

<hr />

FWIW3, I followed these instructions to install Visual Studio Code on my Fedora 34 host:
[Install Visual Studio Code on Fedora 35/34/33/32](https://computingforgeeks.com/install-visual-studio-code-on-fedora/)

**Comment by andreeis** [comment] 2021-12-07 10:15
@fischerjd, when you use the DEBUG button, the extension reads MIMode and miDebuggerPath from settings.json. When you use "F5", it reads them from launch.json. This is by design. Pressing the debug button is not meant to read anything from launch.json.

The dialog you see (with the "launch.json" button) comes from the VSCode debugger, probably since before other extensions (like CMake Tools or this Makefile Tools) were implementing features like on the fly or quick debugging. I imagine this can be improved in future if the debugger APIs will add a field for extensions to specify what button text to have ("launch.json" versus "settings.json"). I'll follow up with the debugger team.

Requiring both settings, again I have to follow up with the debugger team. We don't enforce any rule for those settings. We pass along what we are given. Maybe we (Makefile Tools) should calculate some defaults in case the value is missing. I will find out.

At the end of your GitHub issue post, you mention that F5 works even if you remove MIMode and miDebuggerPath from launch.json, did I understand correct?

@WardenGnaw, any thoughts about all that is brainstormed here?

**Comment by WardenGnaw** [comment] 2021-12-07 18:24
>1. The error message dialog has a button on it labeled Open 'launch.json', but this seems to be the wrong configuration file with which to manage this problem. 

This is due to how the debug flow works in VS Code. Both CMake and Makefile extension build on top of the VS Code C++ Extension's debug adapter and plumb the user information from the settings.json to make a on-the-fly `launch.json` configuration. 

> 2. the configuration settings MIMode and miDebuggerPath must be defined in settings.json, i.e., both settings are required; they are not optional

Not sure why these are required. MIMode should default to gdb if not defined and the debug adapter will use the PATH environment to discover gdb. Side note: This does not apply to those using lldb/lldb-mi.

**Comment by fischerjd** [comment] 2021-12-07 18:50
*   At the end of your GitHub issue post, you mention that F5 works even if you remove MIMode and miDebuggerPath from launch.json, did I understand correct?

Correct.

Jim Fischer
Department of Electrical Engineering and Computer Science
333 Naka Hall
University of Missouri
Columbia, MO  65211
Phone: 1-573-882-4382
Fax: 1-573-882-8318
Email: ***@***.******@***.***>

**Comment by andreeis** [comment] 2021-12-10 18:06
@fischerjd, another question for you, besides the logs and the settings that I asked in my previous reply.
Do you have the CppTools extension installed or not?

**Comment by 1475505** [comment] 2022-05-03 22:54
> 

I met the same problem. Ubuntu20.04, with extension "C/C++". F5 normally but MakefileTools.debug is alerting "miDebuggerPath is invalid". Config "launch.json": /usr/bin/gdb

**Comment by andreeis** [comment] 2022-05-04 21:54
@1475505, please confirm, are you using the "debug" button specific to the Makefile Tools extension or F5? They are not the same. F5 uses your launch.json but the debug button creates a launch.json on the fly with a minimal set of information deduced from all your settings.

**Comment by 1475505** [comment] 2022-05-06 15:14
> @1475505, please confirm, are you using the "debug" button specific to the Makefile Tools extension or F5? They are not the same. F5 uses your launch.json but the debug button creates a launch.json on the fly with a minimal set of information deduced from all your settings.

Thanks, sorry for confusing.

MakefileTools.debug is alerting "miDebuggerPath is invalid".  -> here means the bug icon in Makefile Tools bar.

**Comment by 1475505** [comment] 2022-05-06 17:08
> > @1475505, please confirm, are you using the "debug" button specific to the Makefile Tools extension or F5? They are not the same. F5 uses your launch.json but the debug button creates a launch.json on the fly with a minimal set of information deduced from all your settings.
> 
> Thanks, sorry for confusing.
> 
> MakefileTools.debug is alerting "miDebuggerPath is invalid". -> here means the bug icon in Makefile Tools bar.

That is to say, is it any way to configure the debug mode in Makefile tools explicitly? Just like `launch.json`

**Comment by andreeis** [comment] 2022-05-24 22:55
@1475505, absolutely. Via "makefile.defaultLaunchConfiguration" (at a global level) and more specifically with every launch target you may define via "makefile.launchConfigurations". Both have "miDebuggerPath" and "MIMode" which mean the same and are named exactly the same as in the launch.json.
Let us know if you encounter any issues with these settings.

**Comment by andreeis** [comment] 2023-10-23 15:49
@1475505 , @fischerjd we will close this ticket soon. Let us know if there is anything else that we left unaddressed or if any symptom is still happening for you. Try the latest release.

**Closed** 2024-02-16 15:59 UTC
Labels: suggest-to-close
