### ISSUE TITLE
Extend launch configurations with more needed items

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#111] opened 2021-02-17 07:36 UTC
Good inspiration is CMake Tools with its debugConfig.
One example of important item to add is environment variables.

**Comment by gcampbell-msft** [comment] 2023-07-11 18:50
This seems like a duplicate of #123, closing.

**Comment by andreeis** [comment] 2023-07-11 19:30
Actually not a duplicate of 123 but of https://github.com/microsoft/vscode-makefile-tools/issues/382.
This ticket was more than just env vars, but more fields. Users have been complaining that the makefile debugging is limited because the launch configuration settings support only a subset of what launch.json defines. I am not sure but I think CMake Tools is closer to parity regarding how much debugConfig overlaps with launch.json.

**Closed** 2023-07-12 14:17 UTC
