### ISSUE TITLE
VSCode process 100% CPU, no progress

### ISSUE THREAD

**Issue by walles** [microsoft/vscode-makefile-tools#327] opened 2022-05-19 07:15 UTC
vscode 1.67.2
Makefile Tools v0.5.0
macOS 12.3.1

This is similar to #215, but contains information requested by @andreeis.

The symptoms I'm getting are that:
* I start vscode
* Popup: "Configuring: Generating dry-run output..." / "Source: Makefile Tools (Extension)"
* VSCode (the main process) uses 100% CPU and never stops (I waited 4 minutes)
* The extension's popup never goes away
* Uninstalling the extension worked around the problem

Here's my `extension.log` [as requested here](https://github.com/microsoft/vscode-makefile-tools/issues/215#issuecomment-931028472):

```
Configurations cached at /Users/johan/dev/go/src/github.com/betalo-sweden/widgetsvc/.vscode/configurationCache.log
No path to the makefile is defined in the settings file.
No folder path to the makefile is defined in the settings file.
Always pre-configure: false
Dry-run switches: --always-make,--keep-going,--print-directory
Additional compiler names:
Exclude compiler names:
No current configuration is defined in the workspace state. Assuming 'Default'.
No target defined in the workspace state. Assuming 'Default'.
No current launch configuration is set in the workspace state.
Default launch configuration: MIMode = undefined,
                    miDebuggerPath = undefined,
                    stopAtEntry = undefined,
                    symbolSearchPath = undefined
Configure on open: true
Configure on edit: true
Configure after command: true
Only .PHONY targets: false
Save before build or configure: true
Build before launch: true
Clear output before build: true
Ignore directory commands: true
compile_commands.json path: null
Deduced command 'make ' for configuration "Default"
Saving opened files before build.
Generating configuration cache with command: 'make --dry-run --always-make --keep-going --print-directory'
Writing the dry-run output: /Users/johan/dev/go/src/github.com/betalo-sweden/widgetsvc/.vscode/dryrun.log
Spawning child process with:
 process name: make
 process args: --dry-run,--always-make,--keep-going,--print-directory
 working directory: /Users/johan/dev/go/src/github.com/betalo-sweden/widgetsvc
 shell type: default
Generating dry-run elapsed time: 0.04
Preprocessing: "/Users/johan/dev/go/src/github.com/betalo-sweden/widgetsvc/.vscode/dryrun.log"
Preprocess elapsed time: 0
Parsing for IntelliSense.
Updating the CppTools IntelliSense Configuration Provider.
Parsing dry-run output for CppTools Custom Configuration Provider.
Analyzing line: make: Entering directory `/Users/johan/dev/go/src/github.com/betalo-sweden/widgetsvc'
MAKE -C: entering directory /Users/johan/dev/go/src/github.com/betalo-sweden/widgetsvc
```

Here's the `make --dry-run --always-make --keep-going --print-directory` output:
```
~/d/g/s/g/b/widgetsvc (master|✔) $ make --dry-run --always-make --keep-going --print-directory
make: Entering directory `/Users/johan/dev/go/src/github.com/betalo-sweden/widgetsvc'
echo "------------------------------------------------------------------------"
echo "WIDGETSVC"
echo "------------------------------------------------------------------------"
grep -E '^[a-zA-Z0-9_/%\-]+:.*?## .*$'  Makefile | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $1, $2}'
make: Leaving directory `/Users/johan/dev/go/src/github.com/betalo-sweden/widgetsvc'
~/d/g/s/g/b/widgetsvc (master|✔) $
```

Here's the top of our `Makefile`. Somewhat censored, but I'm guessing this would be what you need:
```
PROJECT_NAME := WIDGETSVC

.PHONY: help
help:
	@echo "------------------------------------------------------------------------"
	@echo "${PROJECT_NAME}"
	@echo "------------------------------------------------------------------------"
	@grep -E '^[a-zA-Z0-9_/%\-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
```

**Comment by walles** [comment] 2022-05-19 07:19
I'm on GNU Make 3.81.

**Comment by walles** [comment] 2022-06-01 11:52
That did work around the startup hang.

**Comment by andreeis** [comment] 2022-06-02 16:57
Closing this as a duplicate of https://github.com/microsoft/vscode-makefile-tools/issues/106.

**Closed by andreeis** 2022-06-02 16:57 UTC
