### ISSUE TITLE
Generating dry-run output appears to hang or take a long time to execute

### ISSUE THREAD

**Issue by JackSabine** [microsoft/vscode-makefile-tools#383] opened 2022-11-09 16:21 UTC
If a command of any rule in the project Makefile has an echo statement with many non-space-delimited dashes (e.g. ~27 or more), the makefile tool will appear to hang.

### 30 dashes: will cause setup to appear to hang
```
foo:
    @echo "------------------------------"
```
 ### 20 dashes: setup processes effectively instantly
```
foo:
    @echo "--------------------"
```
### 2 groups of 15 dashes separated by a space: setup processes effectively instantly
```
foo:
    @echo "--------------- ---------------"
```
### 2 groups of 15 dashes separated by any non-space character: will cause setup to appear to hang
```
foo:
    @echo "---------------x---------------" 
```

(Tested on Ubuntu 22.04 LTS, 18.04, and Pop!_OS 22.04 LTS)

**Comment by bobbrow** [comment] 2022-11-09 17:57
Thank you for the bug report.  This looks like it might be a duplicate of #106.  If not, please let us know and we can reopen it.

**Closed by bobbrow** 2022-11-09 17:57 UTC
