### ISSUE TITLE
Makefile Tools perspective not available

### ISSUE THREAD

**Issue by zyrkiel** [microsoft/vscode-makefile-tools#248] opened 2021-12-07 16:31 UTC
Issue Type: <b>Bug</b>

The tab dedicated to Makefile Tools perspective is not available from Visual Studio Code under remote dev from WSL.

I am running this simple makefile project (last Makefile from the link) on WSL:
https://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/

However, it is not possible to launch the build or gdb on that code from VS code with Makefile Tools and Remote - WSL

Extension version: 0.3.0
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.85GB free)|
|Process Argv|--crash-reporter-id 5a80b593-8b19-45f9-953f-4a044fc20e21|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.73GB (5.85GB free)|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30408636
vscop804:30404766
vs360cf:30404996
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

**Comment by andreeis** [comment] 2021-12-07 20:51
@zyrkiel, thank you for reporting this problem. Until I have a chance to prep my wsl environment and try the project, I have a few quick questions. "Perspective" is the "C/C++" left side UI which contains "configuration", "build target" and "launch target"? And it used to appear for you in 0.2.2 and suddenly disappeared with 0.3.0?
If so, run the command configure manually "Makefile: Configure" (or "Clean Configure") from the palette and this will activate all the UI that is hidden now.
If this is the issue you encounter, it is because the extension activates automatically only if there is a makefile in the root folder (where you open VSCode from). We plan to address smarter activation scenarios (where no makefile is in the root, it is somewhere else and referenced via settings like "makefile.makefilePath" or "makefile.makeDirectory") and we track this with https://github.com/microsoft/vscode-makefile-tools/issues/5.

**Comment by zyrkiel** [comment] 2021-12-08 08:56
Hi @andreeis 

First, I would like to present my project files tree:

/mnt/c/my_path/my_main_project /my_makefile_submodule/src/Makefile
                                                                                                  include/*.h

I wanted to edit and debug my new submodule while staying in my main project folder.

> "Perspective" is the "C/C++" left side UI which contains "configuration", "build target" and "launch target"?

Yes, I call persperctive the UI that enables to configure/build/debug the project via the Makefile Tools extension.

> And it used to appear for you in 0.2.2 and suddenly disappeared with 0.3.0?

No, I have not made it worked before. I just installed it. However, switching for version 0.2.2, closing and reopening my main project folder didn't make the perspective UI appear.

> run the command configure manually "Makefile: Configure" (or "Clean Configure") from the palette and this will activate all the UI that is hidden now.

Running "Makefile: Configure" from Command Palette makes the UI appear, but it is not possible to configure, use it unless the opened folder contained a Makefiles. That's make me impossible to separate the source from the include, and it's less convenient for the creation of a submodule inside a project.

I have tried using the"makefile.Compile Commands Path" "makefile.makefilePath" or "makefile.makeDirectory" but I get this error:

> Executing task: 'make' '-f' '"/mnt/c/my_path/my_main_project /my_makefile_submodule/src"' '-C' '"/mnt/c/my_path/my_main_project /my_makefile_submodule/src"' <  
>  
> make: *** "/mnt/c/my_path/my_main_project /my_makefile_submodule/src": No such file or directory.  Stop.
The terminal process "bash '-c', ''make' '-f' '"/mnt/c/my_path/my_main_project /my_makefile_submodule/src"' '-C' '"/mnt/c/my_path/my_main_project /my_makefile_submodule/src"''" terminated with exit code: 2.


Opening the src folder makes also the UI appear.

I have managed to use my clean and build config to successfully build my sample.  
When trying to debug I got this log and none of my breakpoints were activated:
> =thread-group-added,id="i1"
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
>  
> For help, type "help".  
Type "apropos word" to search for commands related to "word".
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
 Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
Stopped due to shared library event (no libraries added or removed)
Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.
>  
> Breakpoint 1, 0x00000000080011e9 in main ()
Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Symbols loaded.
[Inferior 1 (process 26070) exited normally]
The program '/mnt/c/my_path/my_main_project /my_makefile_submodule/src/exec' has exited with code 0 (0x00000000).

**Comment by andreeis** [comment] 2021-12-08 09:47
@zyrkiel, I will get back to you with more answers for other questions in your report (most are known regressions with 0.3.0 which we'll fix asap).

Quick ask in the meantime. Can you set "makefile.loggingLevel" : "Debug" and "makefile.extensionLog" : ".vscode/extension.log" in /mnt/c/my_path/my_main_project/.vscode/settings.json and share with us the following files from the .vscode subfolder: dryrun.log, extension.log

Before I involve the debugger team, do you confirm that the source files where you set your breakpoints have been compiled with debug information (-g switch?).

**Comment by zyrkiel** [comment] 2021-12-08 10:11
Here is my Makefile:

```
IDIR = ../include
CC=gcc
CFLAGS += -Wall -g -std=gnu99 -I $(IDIR)

ODIR=obj
LDIR =../lib

LIBS=-lm

_DEPS = hellofunc.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = hellomake.o hellofunc.o 
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))


$(ODIR)/%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

exec: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~ 
```

For  the code you can take what is in https://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/

Here is the log files:


[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/7675179/extension.log)
[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/7675180/dryrun.log)

**Comment by andreeis** [comment] 2021-12-09 01:11
@zyrkiel, please manually install the vsix from [this link](https://github.com/microsoft/vscode-makefile-tools/actions/runs/1556708172) and let me know how everything works. It fixes the quoting for when building the makefile.

**Comment by zyrkiel** [comment] 2021-12-09 07:57
Hi,  
Which one ?  
I do not see any difference right now.

**Comment by andreeis** [comment] 2021-12-09 08:03
@zyrkiel, you click on the link, download the vsix, go to the "Extensions" tab on the left side of VSCode, click on "..." on the upper right corner of the "Extensions" tab, click on context menu "Install from Vsix" and point that to what you downloaded from the link.
That should update your Makefile Tools extension with a fix I am testing. I am curious if the fix is complete and whether it addresses correctly all your project.

Or, you are saying that you already installed the vsix and you do not see any improvement? Is the build still failing because of quoting?

**Comment by zyrkiel** [comment] 2021-12-09 08:06
Sorry, I was meaning which quote.

I have updated the extension with your link.

What is the use case you would like me to test?

**Comment by andreeis** [comment] 2021-12-09 08:19
Configure (does it end with a succeeded message in output channel and IntelliSense works?) and build (do you still see the "directory not found" error even when you use -f or -C arguments for make, meaning "makefile.makefilePath" or "makefile.makeDirectory")?

**Comment by zyrkiel** [comment] 2021-12-09 08:52
Ok, I have tested the main Use Case where I am opening with VS Code the PATH:  
/mnt/c/my_path/my_main_project 

I have done some modifications to the makefile, so it can be located outside the src dir. My makefile is now here:  
/mnt/c/my_path/my_main_project/my_makefile_submodule

I have inputed this informations:
- makefile.makeDirectory= /mnt/c/my_path/my_main_project
- makefile.makefilePath = /mnt/c/my_path/my_main_project/my_makefile_submodule/Makefile

I is working well! Thanks. 
I have checked again, that I didn't have a bad config with the 0.3 version, and did not succeed to make the same config work.

Thanks a lot.

I am now asking, how do I make the bind between F5 and the Makefile Tools debug launch?

**Comment by andreeis** [comment] 2021-12-09 09:19
@zyrkiel, glad to hear the problems you had originally with 0.3.0 are fixed. 0.3.1 will be out soon.
I didn't try this before, but I imagine you can open the "Keyboard Shortcuts" tab with the command "Preferences: Open Keyboard Shortcuts" from the palette. You can remove the default VSCode binding for F5 invoking the VSCode Debugger and you can use F5 to the Makefile Tools command for debugging: "Makefile: Debug the selected binary target".
Does this work?

**Comment by andreeis** [comment] 2021-12-10 00:34
Closing this since we just released a fix with Makefile Tools 0.3.1 today.

**Closed by andreeis** 2021-12-10 00:34 UTC

**Comment by yezhengli-Mr9** [comment] 2023-02-26 04:44
> 

Thanks `Makefile: Configure` helps.

**Comment by yezhengli-Mr9** [comment] 2023-02-26 04:44
> @zyrkiel, thank you for reporting this problem. Until I have a chance to prep my wsl environment and try the project, I have a few quick questions. "Perspective" is the "C/C++" left side UI which contains "configuration", "build target" and "launch target"? And it used to appear for you in 0.2.2 and suddenly disappeared with 0.3.0? If so, run the command configure manually "Makefile: Configure" (or "Clean Configure") from the palette and this will activate all the UI that is hidden now. If this is the issue you encounter, it is because the extension activates automatically only if there is a makefile in the root folder (where you open VSCode from). We plan to address smarter activation scenarios (where no makefile is in the root, it is somewhere else and referenced via settings like "makefile.makefilePath" or "makefile.makeDirectory") and we track this with #5. Or it may be another issue and you can confirm that for us before we try your project in WSL.

Thanks `Makefile: Configure` fixes the problem.
