### ISSUE TITLE
How to completely disable --dry-run popup?

### ISSUE THREAD

**Issue by tandav** [microsoft/vscode-makefile-tools#547] opened 2023-12-31 07:31 UTC
This popup is very annoying. If I click Yes (don't show again) it still appears after reboot.
<img width="452" alt="image" src="https://github.com/microsoft/vscode-makefile-tools/assets/5549677/6d35cab0-3c9b-4780-85fa-796516fb27fe">

- macOS 14.0
- Makefile Tools v0.8.22

**Comment by louis222220** [comment] 2024-01-02 07:26
I face the same issue and also have no idea about it.
It have happened for about 1~2 weeks and won't happen when switched to the versions `0.7`.

I hope the following information are helpful.

My system version:
```
MacOS: 13.4.1

Makefile Tools: 0.8.22

VSCode:
  Version: 1.85.1
  Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
  Date: 2023-12-13T09:48:16.874Z
  Electron: 25.9.7
  ElectronBuildId: 25551756
  Chromium: 114.0.5735.289
  Node.js: 18.15.0
  V8: 11.4.183.29-electron.0
  OS: Darwin arm64 22.5.0
```

These log was printed in the output window:
```
No current configuration is defined in the workspace state. Assuming 'Default'.
No target defined in the workspace state. Assuming 'Default'.
Dropping various extension output files at /Users/louis/Library/Application Support/Code/User/workspaceStorage/cb0c9a491211cdcff9f78f177e655e26/ms-vscode.makefile-tools
Logging level: Normal
Configurations cached at /Users/louis/Library/Application Support/Code/User/workspaceStorage/cb0c9a491211cdcff9f78f177e655e26/ms-vscode.makefile-tools/configurationCache.log
No path to the makefile is defined in the settings file.
No folder path to the makefile is defined in the settings file.
Always pre-configure: false
Always post-configure: false
Dry-run switches: '--always-make', '--keep-going', '--print-directory'
No current launch configuration is set in the workspace state.
Default launch configuration: MIMode = undefined,
                    miDebuggerPath = undefined,
                    stopAtEntry = undefined,
                    symbolSearchPath = undefined
Configure on open: true
Configure on edit: true
Configure after command: true
Only .PHONY targets: false
Save before build or configure: true
Build before launch: true
Clear output before build: true
Ignore directory commands: true
compile_commands.json path: null
Deduced command 'make ' for configuration "Default"
The Makefile Tools extension process of configuring your project is about to run 'make --dry-run' in order to parse the output for useful information. This is needed to calculate accurate IntelliSense and targets information. Although in general 'make --dry-run' only lists (without executing) the operations 'make' would do in the current context, it is still possible some code to be executed, like $(shell) syntax in the makefile or recursive invocations of the $(MAKE) variable.
If you don't feel comfortable allowing this configure process and 'make --dry-run' to be invoked by the extension, you can chose a recent full, clean, verbose and up-to-date build log as an alternative, via the setting 'makefile.buildLog'. 
```

**Comment by gcampbell-msft** [comment] 2024-01-02 21:24
This popup is expected, however, it is not expected for it to continually appear in the same workspace upon reboots. I'll mark this as a bug and make sure we prioritize it. 

Thanks for letting us know!

**Comment by gcampbell-msft** [comment] 2024-01-03 14:51
Following up, I have attempted to repro following your steps, basically clicking `Yes (don't show again)`, and then rebooting, and then opening the same workspace again, and I wasn't able to reproduce the issue on either Windows or a Mac. 

Is it possible there is something else at play that I should try to set in my Makefile project in order for it to repro? 

Thanks.

**Comment by dannyskoog** [comment] 2024-01-05 07:35
I'm also seeing the same on macOS 14

**Comment by Moulick** [comment] 2024-01-17 14:11
@gcampbell-msft I do not use workspaces in vscode, instead opening folders directly via command line, this pops up every time. Please add a global setting to disable this popup irrespective of workspace/folder

**Comment by gcampbell-msft** [comment] 2024-01-17 14:15
@Moulick Are you also on Mac? To my understanding, VS Code treats any folder being opened as a "workspace" when it comes to this feature, so it shouldn't matter how you open VS Code. I'm beginning to wonder if there is a bug with how we're persisting the information that's only occurring on Mac. 

Thanks.

**Comment by Moulick** [comment] 2024-01-17 14:18
@gcampbell-msft yes I am on mac. Though, I go out of my way to not save a folder I open as a "workspace". I wish vscode had a way to disable this workspace idea altogether 😄

**Comment by Moulick** [comment] 2024-01-17 14:24
Maybe store the config in the user `settings.json` ? That also has the benefit of being synced across devices

**Comment by Moulick** [comment] 2024-02-21 17:11
One way I can reproduce it is,

1. Open vscode
2. Close all workspaces, clicking "Close workspace"

<img width="268" alt="image" src="https://github.com/microsoft/vscode-makefile-tools/assets/15780903/41148892-a5ef-4aa2-8397-d28e18f59a8c">

3. After closing all workspace, you will still be left with a window.
4. In your terminal, go to a folder that has a makefile
5. Run `code . --add` which adds the folder to an open window.
6. This will trigger makefile tools to give the mentioned error.

Vs code with a recent release has now the option to automatically throw away untitled workspaces `"window.confirmSaveUntitledWorkspace": false`. I have it enabled, but it does not affect the bug, I have checked with both true/false. It probably only makes it occur more often.

**Comment by DoctorHayes** [comment] 2024-02-21 23:03
I have the same issue. I am running it within Ubuntu in the Windows Subsystem for Linux (WSL).

**Comment by gcampbell-msft** [comment] 2024-03-01 12:57
Just giving a quick update here: 

We are investigating ways to improve this experience and ways to improve the annoyance that you all are experiencing. We hope to implement a fix and/or better solution in the near future. 

@Moulick For your issue, I would expect that this is actually expected, because if you are adding a new folder that you haven't opened before to your workspace, then our extension will treat this as a new folder that hasn't had that pop-up yet. 
However, if it's happening for folders that have already done that, then yes, this is a bug. 

Thanks everyone for your understanding.

**Comment by Moulick** [comment] 2024-03-01 13:22
Thank you @gcampbell-msft. Yes, even if I add the same folder, this pops up. Also maybe this extension can instead of having it's own trust setup, rely on VSCodes workspace trust https://code.visualstudio.com/docs/editor/workspace-trust ? Using these settings the user can control how the extension can behave. 
<img width="768" alt="image" src="https://github.com/microsoft/vscode-makefile-tools/assets/15780903/dcd024fc-a634-42d9-8638-7233aab88634">

**Comment by Yingzi1234** [comment] 2024-03-07 08:36
@Moulick Thank you for your answer! Do you mean re-cloning an identical folder or re-extracting a folder? If so, the appearance of the trust prompt box should be expected. If you don't want the trust box to appear you can reset it in VS Code as described below(based on https://code.visualstudio.com/docs/editor/workspace-trust), thanks!
![image](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/9a06d550-d60d-4c4a-ba18-35a3e829c28b)

**Comment by Moulick** [comment] 2024-03-07 09:30
@Yingzi1234 I mean simply re-opening the exact same folder again in vscode triggers the popup. I have disabled the workspace trust and set it to trust all folder. VS code itself does not prompt me for trust anymore, Only the VSCode makefile extension.

**Comment by gcampbell-msft** [comment] 2024-03-07 14:32
@Moulick Thanks for the confirmation, we are looking into this, I appreciate your patience.

**Comment by sinemakinci1** [comment] 2024-03-11 21:10
Just wanted to update the thread here that we are redesigning the initial configure experience, and proposing removing the dry-run popup for ease of use for users and so popups do not persist. 

If you would like to add any additional comments on this effort, please see our issue #572

**Comment by mobynet1** [comment] 2024-03-16 20:45
This happens over and over and over and over - Yes (don't show again - but I will just to annoy you) and over and over and over... I think you get it. The pop-up is EXTREMELY annoying. I am using Visual Studio Code v1.87.2 on Windows. It would really be great if I said - No! Please don't again! and then it should never see the light of my screen ever again...

Or, if there was a flag that could turn it off, that would be great. I did set a makefile.dryrunSwitches flag, "--dry-run" to no avail. Bottom line is if the user says "never show this notification ever, ever, ever again" the program should honor that request!!

**Comment by gcampbell-msft** [comment] 2024-03-29 13:19
@mobynet1 @tandav @Moulick We have merged #573, and it will be available in pre-release in the next couple of hours.

**Comment by Moulick** [comment] 2024-03-30 11:05
Thank you guys for all your efforts. Running version `v0.10.2 (pre-release)`, I do not get any prompt at all, not even once. Aren't I supposed to get the prompt at-least once to allow dry run?

**Comment by gcampbell-msft** [comment] 2024-04-01 13:49
@Moulick No. We are following VS Code's support of the idea of `Workspace Trust`. If you have "trusted" your workspace, we respect that and allow for configuring with "dry-run" to happen. However, if you don't enable workspace trust, we don't enable the extension, therefore ensuring that nothing from our extension happens.

**Comment by Moulick** [comment] 2024-04-01 13:51
That sounds fantastic. This fixes the problem. Thanks!

**Comment by Yingzi1234** [comment] 2024-04-11 03:17
Happy to see your issue has been resolved, thanks for contributing to Developer Community.

**Closed** 2024-04-24 14:53 UTC
Labels: bug, more info needed, fixed-pending-release
