### ISSUE TITLE
The output message in the output box will appear three times repeatedly

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-makefile-tools#606] opened 2024-06-21 02:08 UTC
**More info:**
1. This issue is reproduced on Windows, Linux, and Mac platforms
2. This issue only occurs the first time vscode is used

**Repro steps:**
1. Open VScode and clone this repo [https://github.com/remonbonbon/makefile-example.git](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fremonbonbon%2Fmakefile-example.git&data=05%7C02%7Cv-cathyzhang%40microsoft.com%7C47a77388299549041afb08dc91304fcd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638544883966674017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=srnOOXRP4%2BVvyWo6ccAsq3m441HQwZlRHavIIb5ZBQA%3D&reserved=0)
2. Open settings page 
3. Search for ”makefile.alwaysPreConfigure” setting and enable it
4. Check that the output window is displayed correctly

**Expected result:**
The output window is displayed correctly
![image](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/dbc95926-14ad-4abc-9550-fd79b8216691)

**Actual result:**        
The output message in the Output window will be repeated three times    
![image](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/d92eced7-bbb3-4df9-b7e8-2745332b7f74)

**Videorecord:**
![issue1](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/5b1d60f4-97b5-4e13-80cf-b433eb441606)

**Comment by gcampbell-msft** [comment] 2024-07-22 13:18
I'm not able to reproduce this, does this reproduce every time? Either way, I plan to close as won't fix due to the low priority nature of this bug.

**Closed by gcampbell-msft** 2024-07-22 13:18 UTC
Labels: bug
