### ISSUE TITLE
Launch Configurations Path Length

### ISSUE THREAD

**Issue by jlwoolf** [microsoft/vscode-makefile-tools#300] opened 2022-03-31 18:16 UTC
When trying to make a launch configuration on WSL, the configuration only works using a direct path to the file. The issue that I have, however, is WSL paths tend to be quite long. As a result, it is hard to tell what configuration I'm selecting. For instance, the below configurations differ by one parameter input. However, when selecting, I cannot determine which is which is which.

```json
"makefile.launchConfigurations": [
        {
            "cwd": "/mnt/c/Users/jlwoolf/Documents/School/spring-2022/csci564/csci564-project2/cachesim",
            "binaryPath": "/mnt/c/Users/jlwoolf/Documents/School/spring-2022/csci564/csci564-project2/cachesim",
            "binaryArgs": [
                "LRU",
                "32768",
                "2048",
                "4",
                "SEQUENTIAL",
                "2"
            ]
        },
        {
            "cwd": "/mnt/c/Users/jlwoolf/Documents/School/spring-2022/csci564/csci564-project2/cachesim",
            "binaryPath": "/mnt/c/Users/jlwoolf/Documents/School/spring-2022/csci564/csci564-project2/cachesim",
            "binaryArgs": [
                "LRU",
                "32768",
                "2048",
                "4",
                "SEQUENTIAL",
                "4"
            ]
        },
        {
            "cwd": "/mnt/c/Users/jlwoolf/Documents/School/spring-2022/csci564/csci564-project2",
            "binaryPath": "/mnt/c/Users/jlwoolf/Documents/School/spring-2022/csci564/csci564-project2/cachesim",
            "binaryArgs": []
        }
]
```
![image](https://user-images.githubusercontent.com/60640764/161123716-1514de1e-0b3c-4e4e-b515-5b59a3758ade.png)

What I was wondering is if there is anyway to have it such that the options appear more compact. And if not, would these be possible additions?

Use a variable in the display. This would also require that ${workspaceFolder} actually works, because right now I cannot use it as an argument in binaryPath:
![image](https://user-images.githubusercontent.com/60640764/161120385-971d4db6-9f62-4d27-b030-a5cf337832a2.png)

Or have a parameter called "name" or something that replaces the path in used for displaying:
![image](https://user-images.githubusercontent.com/60640764/161121945-1f065d12-c42a-4fc3-a9fa-b140ce6b2327.png)

Or be able to disable the path entirely:
![image](https://user-images.githubusercontent.com/60640764/161122602-d89d3517-e264-4426-9743-f03d09a91d1a.png)

All of these options would be amazing, but the second and third would likely be the easiest to implement. This would help a lot. Thank you.

**Comment by andreeis** [comment] 2022-03-31 19:03
@jlwoolf, yes we are aware of this inconvenience. We will implement variables expansion in the future, so ${workspaceFolder} and other things will work.
In the meantime, don't you see a more detailed UI hint when you mouse over each entry, like tooltip? I will also try soon and confirm.

**Comment by jlwoolf** [comment] 2022-03-31 22:10
@andreeis  Totally understand. This did bother me enough though that I just submitted a pull request with the naming feature implemented, if you would like to check that out.

**Comment by andreeis** [comment] 2022-04-21 21:57
@jlwoolf, I see that you closed your PR https://github.com/microsoft/vscode-makefile-tools/pull/301. Was that by mistake? Do you still want us to look at it?
I did test it and found some issues but stopped when I realized that you actually had closed it.

**Comment by jlwoolf** [comment] 2022-04-22 00:06
I closed it as my implementation was a bit sloppy and rushed. I planned to improve it but got fairly busy. If you want I can reopen it.

**Comment by andreeis** [comment] 2022-04-25 20:32
@jlwoolf, no problem. When you get back to it, have a closer look at what's happening in src/make.ts parseLaunchConfigurations regarding the reading/setting of launchTargets global in src/configuration.ts. Your PR changes how that is set, possibly because many variables names are a bit confusing. There is a comment explaining the difference between a launch target and a launch configuration at the end of src/configurations.ts. Test the content of the quick pick for clean configure versus non clean configure (there are some issues now around that, in the PR).

**Comment by bobbrow** [comment] 2022-08-24 16:51
@jlwoolf I didn't notice earlier, but now I see that you published a copy of our extension with this change in it back in March.  To avoid fragmenting the community I think it would be better to get the change into our extension so that everyone can have it.  Is there interest in completing the PR?  Would you like us to finish it for you?

**Comment by jlwoolf** [comment] 2022-11-14 05:58
@bobbrow I got quite busy so if you'd like to finish it for me that would be great. Still learning the intricacies of github so if need to do something to enable/aid in your continuation of this PR let me know. 

So sorry I didn't respond sooner.

**Comment by gcampbell-msft** [comment] 2023-11-17 19:19
@jlwoolf We implemented initial variable expansion support with this PR: #457. I am marking this as fixed, but please let me know if this is not correct. Thanks!

**Comment by gcampbell-msft** [comment] 2023-11-17 19:27
@jlwoolf My apologies, it seems like we have some work to do for adding our variable expansion to other locations and configurations. Removing the `fixed-pending-release` label.

**Comment by gcampbell-msft** [comment] 2023-12-05 16:14
@jlwoolf Could you confirm for me, is this issue fixed for you in the current version of the extension? I'm not able to reproduce your issue right now. 

Thanks!

**Closed** 2023-12-14 18:08 UTC
Labels: enhancement, fixed-pending-release, IMPORTANT
