### ISSUE TITLE
Issue with Makefile: incompatible language modes

### ISSUE THREAD

**Issue by arayq2** [microsoft/vscode-makefile-tools#443] opened 2023-03-24 03:27 UTC
I open my C++ project and the Makefile in it is annotated with an orange '1'. Opening the file shows an orange cursor at the beginning of the file. The Problems tab says:
command-line error: language modes specified are incompatible C/C++ (1027) [Ln 1, Col 1]
 
What does this message mean?  Which component is generating it?  What "language modes' (in plural) is it referring to?  What is the incompatibility? 

From all indications, the Makefile was successfully parsed for configuration, Then, I was able to invoke a build of 'all' (which is also the first target in the file) and it ran to completion successfully.  In other words, everything _works_ as expected.  Yet there is this inscrutable, utterly uninformative "errror" message.  How can I get rid of it?

The Makefile has settings such as:

 CXX = g++
CXXFLAGS = -g -pthread -m64 -std=c++14 -Wall

and .vscode/c_cpp_properties.json has:

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.makefile-tools",
            "compileCommands": "${workspaceFolder}/compile_commands.json"
        }
    ],
    "version": 4
}

```
What extra magical incantations do I need to make a bog standard project acceptable to the Makefile Tools add-in?

**Comment by gcampbell-msft** [comment] 2023-03-24 13:48
@arayq2 Thanks for the report! A couple of clarifying questions:

1. Is this happening in some of your code files? Or is this happening inside of the Makefile itself.
2. Could you provide a screenshot so that I can more distinctly see and know what you're referencing? 

Thanks!

**Comment by arayq2** [comment] 2023-03-24 18:26
Other info:
Makefile Tools version: 0.6.0
G++ version: 11.3
Gnu make version: 4.3
Environment (Linux): Ubuntu 22.04

**Comment by andreeis** [comment] 2023-03-24 18:43
Is your project open source or easy to package for us to repro on our side?
In case things cannot be shared with the world, we've been using successfully so far the microsoft email makefiletools@microsoft.com with other users.

**Comment by gcampbell-msft** [comment] 2023-03-24 19:41
@arayq2 Additionally, if you feel comfortable, could you send us a list of your installed extensions? I'm curious if you have other extensions installed that may try to provide Intellisense for the Makefile itself. Thanks!

**Comment by arayq2** [comment] 2023-03-24 19:48
@andreeis 
Sorry, no, the code is not open source.  At present, a good portion of it is proprietary, and some of that will probably have to remain so.  Other parts are either public domain or open source (MIT license).  That's why I'm hesitant to pass along the dryrun.log and extension.log files: although from inspecting them, nothing unusual or unexpected seems to be present.    The dryrun.log looks exactly like the output of running make on the command line with the '-n' option.  A large part of the extension.log file is just the details of compiling individual files.  If I edit those lines out, leaving only the "meta" information, will that be enough?

**Comment by arayq2** [comment] 2023-03-24 20:14
@gcampbell-msft  
I'm using the Remote-SSH extension to run a VSCode session on a Linux box from a Windows 10 box (both machines on a local home network.) I have these extensions installed in this instance: C/C++; C/C++ Extension Pack; CMake; CMake Tools; GitLens; MakeFile Tools; along with C/C++ Themes installed "globally" in the underlying VSCode instance.  Could the CMake extensions be running interference here (there is no CMakeLists.txt file anywhere)?  Where would they be logging their activity?

**Comment by andreeis** [comment] 2023-03-24 20:43
@arayq2, no interference with CMake Tools (especially if no CMakeLists.txt is present).
In the extension.log, do you see any "Sending configuration" and on the same line, instead of c/c++ source file we would pass along the makefile file ? Any "not found" message in the same "extension.log" associated with the makefile file?

@sean-mcmanus, @Colengms judging from the "C/C++" hint in the problems tab, the CppTools extension emits this problem, correct? Any ideas here?

**Comment by sean-mcmanus** [comment] 2023-03-24 20:49
We need to see the C/C++: Log Diagnostics. The "incompatible language modes" is usually when there's a C versus C++ mismatch, i.e. a -std for C++ is sent for a file we believe is C or vice versa.

**Comment by arayq2** [comment] 2023-03-26 01:13
UPDATE: As mysteriously as the issue appeared, so has it disappeared!  And I can't reproduce it. :-(  All I did was to disable a couple of extensions (specificially, CMake and CMake Tools), reload the project, and when that didn't so anything, re-enable those extensions, and instead of reloading the project, I quit VSCode altogether and started over.  And lo, it was gone.   

I had this issue with another project - again, just the Makefile - which I "solved" by fiddling with the values in the c_cpp_properties.json file of "cStandard" and "cppStandard".  That "solution" didn't work here (which is why I didn't mention it).  

But for future reference something along the lines of disabling/re-enabling extensions along with re-starting VSCode _may_ be a viable workaround.  It seems to be a common type of resort for inscrutable errors with any Microsoft product ("if all else fails, re-start/re-boot/re-install") ...

**Comment by arayq2** [comment] 2023-03-26 01:24
@andreeis 
For completeness:  The "Sending configuration" lines in the extension.log were of two kinds: first, 70 lines of "Sending configuration (from cache)" for every distinct source file in my ./src subdirectory, followed by 88 lines of "Sending configuration for file" for the same files with some repeats.  And no lines at all with "not found".

**Comment by andreeis** [comment] 2023-03-26 19:59
Interesting :). Not closing this though, we can still gather more clues.

@arayq2. Please provide the C/C++ Diagnostics log for @sean-mcmanus and @Colengms to look at. If you already did and I didn't see, I apologize. Run the diagnostics command after you see the red squiggle, after you open the makefile file (when you happen to reproduce again, hopefully soon for the sake of getting to the root cause).

@arayq2, thank you for the Makefile Tools logs. Those look good. From what I see, I don't see the Makefile extension trying to convince CppTools that we provide IntelliSense for makefile. @gcampbell-msft, you need to investigate the same on CMake Tools side. Is CMake Tools trying to create an IntelliSense configuration entry associated with the makefile file instead of only c/c++ files? (not sure if CMake Tools has some equivalent logging for 'Sending configuration for...'). Also, is CppTools asking for IntelliSense configuration and requesting the makefile path instead of a c/c++ source file path? The equivalent for "not found" in the logging. We can follow up offline and find where that logging is how it is phrased so that @arayq2 searches for it in the CMake Tools output channel. Then we either find CMT as the culprit or we rule it out.

@sean-mcmanus , regarding the CppTools issue 9684 which you referenced above... I see they moved on to CMake, so I'm not replying there but to summarize my experience with all the occurrences of this CppTools squiggle message (on C/C++ source files, never on makefiles until this one :) ). It always happened, no exception, for c/c++ source files that we (Makefile Tools) were not providing CppTools configurations for: either because we had parser bugs which we fixed or because the users were opening files from outside the scope of their builds, meaning our "make --dry-run --always-make" was not producing an output that contained a compiler/linker command with the opened file... or users had some by design issues with --always-make, had to remove it and their files were up to date, our "make --dry-run" was not seeing them in the output (outside of our control).

**Comment by arayq2** [comment] 2023-03-27 14:08
@andreeis 
For clarity, there was no red squiggle, only a caret cursor at llne 1 column 1 of the Makefile.  That first line was (and still is) completely empty.  I even tried adding a shebang line ('#!/usr/bin/make -f'), just in case the parser was looking for that (!), to no effect.

The C/C++ Diagnostics output looks like this:
```
-------- Diagnostics - 3/25/2023, 9:03:24 PM
Version: 1.14.5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "[[PROJECT_DIRECTORY]]/include/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/g++",
    "cStandard": "c11",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.makefile-tools",
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "${workspaceFolder}/include/**",
            "${workspaceFolder}"
        ]
    },
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false
}
Custom browse configuration: 
{
    "browsePath": []
}
No active translation units.
```

**Comment by sean-mcmanus** [comment] 2023-03-27 17:37
@arayq2 The C/C++: Log Diagnostics needs to be run after opening a file (after it's been reproing the error message about incompatible language modes), assuming you can still repro that.

**Comment by andreeis** [comment] 2023-07-11 08:43
@arayq2 I am closing this ticket but please reactivate if you still reproduce this issue and as Sean says, run the Log Diagnostics command after you open the file with the problem.

**Closed by andreeis** 2023-07-11 08:43 UTC
Labels: more info needed
