### ISSUE TITLE
Argument parsing is incorrect (e.g. -g file.cpp is grouped as an argument)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-makefile-tools#142] opened 2021-03-29 20:26 UTC
Originally reported at https://github.com/microsoft/vscode-cpptools/issues/7252 .

The argument parsing code doesn't handle the cases where a flag taking a single argument (e.g. -g) is followed by the filename. It's sent to the cpptools extension as "-g file.cpp" which we don't currently support.

**Comment by Colengms** [comment] 2021-03-29 20:57
Cpptools expect compilerArgs to be individual command line args (as see by the shell).  If an arg is multi-part, each part should be separate.  Note that some args are 3 or 4 part (some Darwin options, such as -sectobjectsymbols, -segaddr, -sectalign, etc.), and secondary args can start with a "-", such as when using -XClang or -Xlinker.

**Comment by andreeis** [comment] 2021-03-29 21:07
Thank you both for investigating up to the root cause and for giving this extra info, I wasn't aware of this requirement.

**Comment by MiguelGuthridge** [comment] 2021-04-03 11:01
Sorry, can someone clarify how to fix this? I'm running Ubuntu 20.04 in WSL 2. Building the project works perfectly, both for the extension and for calling `make ...` manually.

I have a project in the default state provided by the extension, and am getting the same errors as above (as well as some with `stdbool.h`). 

I can't find references to `compilerArgs` in any configuration files that I am aware of (`c_cpp_properties.json`, `settings.json`), and I'm not sure where to look for them. Is this be `CFLAGS` in my Makefile? If so, how can I get them to work properly?

Also, I'm unsure why I would be encountering issues like this with the default settings of a reasonably standard project with a reasonably standard Makefile.

Am I doing something wrong here, if so what, and how can I fix it?

**Comment by andreeis** [comment] 2021-04-05 06:32
@MiguelGuthridge, this is a bug in the Makefile Tools extension and I can't think of a workaround at the moment. We will fix this asap and it will be part of our upcoming 0.2.1 release. Once the fix is in the GitHub repository you will be able to get unblocked before the official release date by manually installing a vsix with the fix. We'll let you know once we fixed this problem.

**Comment by sean-mcmanus** [comment] 2021-04-05 16:42
A workaround may be to move the "file.cpp" to the end of all your compiler arguments in your makefile.

**Comment by andreeis** [comment] 2021-04-28 08:22
@MiguelGuthridge, you can find a vsix with the fix for this problem at https://github.com/microsoft/vscode-makefile-tools/actions/runs/791925873. Installing that (with the "Extensions: Install From VSIX" command in the palette) can unblock you until we release Makefile Tools 0.2.1. Let us know if you find any issues.

**Closed** 2021-05-06 21:29 UTC
