### ISSUE TITLE
GDB not stopping at break point when using Makefile Tools extension

### ISSUE THREAD

**Issue by aman-user** [microsoft/vscode-makefile-tools#189] opened 2021-06-23 12:41 UTC
Hi ,

I am trying to debug https://github.com/snap-stanford/snap/tree/master/examples/cesna
i have build the project using [makefile-tools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools) with [Makefile](https://github.com/snap-stanford/snap/blob/master/examples/cesna/Makefile) 
after the binary got generated.  I am trying to debug with option "DEBUG" in makefile-tools

I have added the -g flag to C++

But it is not hitting the break point and exiting with debug log

Log from debug console

=thread-group-added,id="i1"
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
Stopped due to shared library event (no libraries added or removed)
Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, 0x000055555558bc00 in main ()
Loaded '/lib/x86_64-linux-gnu/libstdc++.so.6'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libm.so.6'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libgomp.so.1'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libgcc_s.so.1'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libpthread.so.0'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libdl.so.2'. Symbols loaded.
[New Thread 0x7ffff7a0f700 (LWP 120627)]
[New Thread 0x7ffff720e700 (LWP 120628)]
[New Thread 0x7ffff632a700 (LWP 120629)]
[Thread 0x7ffff632a700 (LWP 120629) exited]
[Thread 0x7ffff720e700 (LWP 120628) exited]
[Thread 0x7ffff7a0f700 (LWP 120627) exited]
[Inferior 1 (process 120622) exited normally]
The program '/home/horizon/repo/snap/snap/examples/cesna/cesna' has exited with code 0 (0x00000000).

**Comment by andreeis** [comment] 2021-06-23 16:51
Closing as a duplicate of https://github.com/microsoft/vscode-makefile-tools/issues/188 (just one GitHub issue earlier than this).
I am investigating. In the meantime, maybe setting "makefile.defaultLaunchConfiguration.stopAtEntry": "true" in your .vscode/settings.json can help at least break at the beginning of your program?

Also, has this ever worked for you?

Thank you for giving a repro, I will try it on my side shortly.

**Closed by andreeis** 2021-06-23 16:51 UTC
Labels: duplicate

**Comment by andreeis** [comment] 2021-06-23 21:37
@aman-user, I just tried the snap project and I am debugging fine on linux after changing the compilation switch -O3 with -g. I debugged cesna and circles from the examples folder. This was after building for the very first time after simply replacing -O3 with -g in makefile.config.

Then I tried to make the change to debug as it looked that is recommended from the comments. I uncommented the CXXFLAGS with -g, -rdynamic and -ggdb and the binaries weren't even built, but it wasn't obvious from the build log what happened. Once I switched back to -g instead of -O3 (what I did first time) I continued to have problems building these binaries. They succeed in being created only if I use -O3 (which is not debug-able of course).

Until I figure out what happens in the build now, at least you can experiment on your side with -ggdb and -rdynamic, maybe they cause the problem you are seeing. Remove each of them, both, etc... try and let me know how debugging works.

**Comment by andreeis** [comment] 2021-06-23 22:10
I was able to debug fine using -g and -ggdb and -rdynamic, so no problem with these switches. But if O3 is also present then the example binaries are not successfully built (and I don't see relevant error messages about their cpp files so I don't know why). Rewrite that portion of makefile.config so that when you use debug, O3 is not included.

Also, instead of commenting/uncommenting flags in the makefile, what do you say about adding a variable that would be passed to make like "make all BUILD_TYPE=DEBUG" and in makefile.config you "if" based on that to define CXXFLAGS for debug and release. Then in .vscode/settings.json you define "makefile.configurations" with 2 entries, debug and release, for each passing "makeArgs": "BUILD_TYPE=DEBUG" or "BUILD_TYPE=RELEASE".
If my suggestion is not clear let me know and I can write (and test) the snippets.

**Comment by aman-user** [comment] 2021-06-24 07:52
Thanks it is working fine only thing is even if i do step over (F10) it is going step into (F11)

**Comment by andreeis** [comment] 2021-06-24 15:57
Glad to hear.
