### ISSUE TITLE
.inc File Types Ignored

### ISSUE THREAD

**Issue by zachgillette** [microsoft/vscode-makefile-tools#460] opened 2023-04-18 14:13 UTC
Our program uses shared C code snippets separated into .inc files that are included in multiple C programs. They are unrecognized by the Intellisense and report compile errors erroneously, as though they are completely ignored. However, the compiler still attempts to compile the .inc files if you open them as if they are their own program. This causes almost universal errors in the .inc file.

**Comment by andreeis** [comment] 2023-04-18 18:52
@zachgillette , since ".inc" is not a file extension that VSCode would normally associate with the "C/C++" language, you can help by adding this in the ".vscode/settings.json":

"files.associations": {
   "*.inc": "c"
}

Also note, since these are (I assume) header files and not c/c++ source files, their IntelliSense exists only in the context of the c/c++ source that includes them, forming together a translation unit. Not having IntelliSense (or having some default, not necessarily accurate) is by design when an .inc (or .h header) file is opened in VSCode without it's c/c++ inclusion counterpart.

If you have IntelliSense problems for the .inc files while also having their inclusion sources opened in VSCode, we need to investigate. If so, please set "C_Cpp.loggingLevel": "Debug" in the same ".vscode/settings.json", then run the command "C/C++ Log Diagnostics" from the palette, after opening the c/c++ file that includes the .inc file. Share the output of the "C/C++ Diagnostisc" channel.

I am also adding @Colengms from the CppTools team, which is the extension that is doing the actual IntelliSense. Makefile Tools is only providing information to CppTools to calculate accurate IntelliSense.

**Comment by zachgillette** [comment] 2023-04-18 19:13
I have already associated the files in the settings. The files are not header files, they are groups of functions that are shared between multiple programs.

I've attached the C/C++ Log Diagnostics output. The issue persists that a const variable declared in the .inc is not found in the file including it. The .inc file itself compiles normally and Intellisense works.

[c.log](https://github.com/microsoft/vscode-makefile-tools/files/11265459/c.log)

**Comment by andreeis** [comment] 2023-04-18 21:06
@zachgillette , it looks all is good from the CppTools side but Makefile Tools doesn't send custom configurations for edi204.c and any other c source file. Time for more logs. But if it's the same project as issue 460, I already saw extension.log but I didn't see dryrun.log. Also, I saw that you selected target "make" which I don't believe you intended. Make sure you either have target "all" or no target at all (empty) selected. After that, regenerate dryrun.log and extension.log as described in https://github.com/microsoft/vscode-makefile-tools/issues/459 and send to us. It is possible that after you make sure you have an empty build target and you open the workspace from the same root folder as you run "make" from in the terminal, both issues 459 and 460 will be solved.

**Comment by zachgillette** [comment] 2023-04-19 18:01
Here they are. This is the same project as 459.
[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/11276343/extension.log)
[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/11276345/dryrun.log)

**Comment by andreeis** [comment] 2023-04-19 19:50
@zachgillette, no IntelliSense configuration sent to CppTools because of the same errors of "make" as in the other issue. We'll focus on 459 to fix first, then I'll get back to this. So far, it's about folders. I need to understand why the extension uses -f (do you set "makefile.makefilePath"?), from what folder are you opening in VSCode as workspace root, from what folder are you running "make" in the terminal and it succeeds.... Maybe we need -C as well... it's all about "make" not finding various referenced includes in the makefiles.

**Comment by andreeis** [comment] 2023-04-19 21:24
Ok, I need new dryrun.log and extension.log, with the latest changes: ignoreDirectoryCommands true, makefilePath as you always set it and the new makeDirectory. Don't forget loggingLevel debug.

**Comment by zachgillette** [comment] 2023-04-19 21:33
Change of plan. I did some analysis with another programmer and this is not about the .inc file. I checked elsewhere and they work fine there.

In this one case, I happened on a file billing.c that uses the system variable PATH_MAX. The .inc is unrelated - it only redefines PATH_MAX when it is not defined. This seems to be that the compiler can't read a system file that we are trying to locate.

**Comment by andreeis** [comment] 2023-04-19 21:44
I understand, glad that you are unblocked. Then, unless anything else changes, I am closing the ticket and please reopen (or create a new one) if you encounter any other problem with the extension. We'll be happy to help and investigate.

**Closed by andreeis** 2023-04-19 21:44 UTC
