### ISSUE TITLE
Unable to build - Target pattern contains no '%'

### ISSUE THREAD

**Issue by 01tot10** [microsoft/vscode-makefile-tools#498] opened 2023-08-30 10:59 UTC
Hey,

I tried the VSCode Makefile Tools for the first time, but I'm getting an error trying to build my project.

I'm running Ubuntu 22.04.3 LTS, with GNU Make 4.3.
I'm building a project, where the Makefile is stored under `./Builds/LinuxMakefile/Makefile`.
I set the path for the Makefile in the extension preferences, as instructed [here](https://earthly.dev/blog/vscode-make/).
When building my target (`all`), I'm getting the following error.

```
Executing task: 'make' 'all' '-f' '/home/tot/DATA/Projects/modern-rt-audio-course/projects/ParametricEQ/Builds/LinuxMakefile/Makefile' 

/home/tot/DATA/Projects/modern-rt-audio-course/projects/ParametricEQ/Builds/LinuxMakefile/Makefile:146: *** target pattern contains no '%'.  Stop.

 *  The terminal process "/usr/bin/zsh '-c', ''make' 'all' '-f' '/home/tot/DATA/Projects/modern-rt-audio-course/projects/ParametricEQ/Builds/LinuxMakefile/Makefile''" failed to launch (exit code: 2).
```

If I execute `make all -f /home/tot/DATA/Projects/modern-rt-audio-course/projects/ParametricEQ/Builds/LinuxMakefile/Makefile` from terminal, everything works as expected. Here's the Makefile I'm trying to execute (with added `.txt`-ending)
[Makefile.txt](https://github.com/microsoft/vscode-makefile-tools/files/12474834/Makefile.txt)

Any idea what could be the cause?

**Comment by gcampbell-msft** [comment] 2023-08-31 13:54
@01tot10 I wonder if this would assist you at all? https://stackoverflow.com/questions/46008706/makefile-target-pattern-contains-no

I don't see that error message in our code, so I think it's coming from Make itself. Though it does seem odd that it's working on the command-line. 

Is there any way you could send your repro project for me to attempt to reproduce the issue?

**Comment by 01tot10** [comment] 2023-09-02 11:06
Thanks for the help @gcampbell-msft.

I also find it odd that the call works from command line, but not from VSCode. Thus, I have the feeling that the Makefile itself should be fine.

Here's the project I was trying to compile
https://github.com/Neural-DSP/modern-rt-audio-course/tree/main/projects/ParametricEQ
You should be able to add the Makefile I uploaded to `Builds/LinuxMakefile/Makefile` relative to `ParametricEQ` to have a similar setup to mine.

**Comment by gcampbell-msft** [comment] 2023-09-07 13:43
@01tot10 Thanks for the information. We will attempt to reproduce and investigate the issue as soon as we have bandwidth.

**Comment by andreeis** [comment] 2023-10-12 13:11
@01tot10 , can you define the following settings 
"makefile.loggingLevel": "Debug",
"makefile.extensionOutputFolder": "./MyOutputFolder",
"makefile.extensionLog": "extension.log"

then reload the project in VSCode, let it configure, then do the build that fails. Then share from MyOutputFolder dryrun.log and extension.log

Maybe the difference between your terminal and how VSCode invokes "make" for building is in the quoting of arguments. The debug log will show some extra details about quoting. Then you can try in the terminal the command as we will see it in the log and maybe reproduce outside VSCode, which may indicate to us to try other variations in how to use VSCode tasks (which is the general VSCode functionality that supports our build invocation). If there is a fix on our side, might be in how we create the task but it could also be a vscode bug related to tasks... Also maybe the terminal types are different...

**Comment by 01tot10** [comment] 2023-10-29 07:52
Hey @andreeis! Thanks for the reply.

I tried to reproduce the problem again, and I think I was mislead in my initial message, since the symptoms appear a bit different actually..

Now, when I call
`make all -f 'Builds/LinuxMakefile/Makefile'`
from the project directory, I'm actually getting the same error message as reported earlier:
`/home/tot/DATA/Projects/modern-rt-audio-course/projects/ParametricEQ/Builds/LinuxMakefile/Makefile:146: *** target pattern contains no '%'.  Stop.`

On the other hand, changing the command line directory before executing `make` commences the build, so either:
`make -C Builds/LinuxMakefile/`
or 
`(cd Builds/LinuxMakefile/ && make)`

Thus, it seems like the Makefile itself is somewhat correct (sidenote: it is automatically generated by [JUCE](https://juce.com/)), but somehow `make` can't interpret it from any other folder. Since this happens also in terminal, I feel like VSCode Makefile Tools might not be the culprit after all.. 

Should I still try your proposition to help finding a cure?

**Comment by gcampbell-msft** [comment] 2023-12-05 19:09
@01tot10 Apologies for the delay in responding. Since the issue is happening on the command-line (outside of this extension), then yes, I would say it is likely that makefile tools isn't the issue. 

However, one thing that you could try, is to set the `makefile.makeDirectory` setting in the extension, which may allow your workaround to work!

With possible workaround and it seeming like this issue is not on the extension, I'm going to close this issue. Please feel free to let me know if there are still issues by opening a new issue if problems persist. Thanks!

**Closed by gcampbell-msft** 2023-12-05 19:09 UTC
Labels: bug, repro needed, Build
