### ISSUE TITLE
Makefile extension stopped working for a certain folder

### ISSUE THREAD

**Issue by George-Gi** [microsoft/vscode-makefile-tools#345] opened 2022-07-22 10:29 UTC
I have the following weird case.
I had setup successfully the tool to work for a certain folder/project by filling in the **Make Directory**, **Makefile Path** and **Make Path**. However, at some point, I don't recall what changed, the Makefile Tool icon stopped appearing on the left, i.e. which means it cannot find the Makefile.
Now I tried to uninstall the VSCode the extensions and the deleted the settings, but the issue is not fixed.
If I choose as a folder in the VSCode a sub-folder of the project, then with the same Makefile Tool settings, the Makefile is located.

I noticed, that for my initial folder, which Makefile Tool stopped working, I don't get anymore the following message.
![image](https://user-images.githubusercontent.com/28848266/180420238-52602e10-f965-4cff-b9e4-d0d4832b0a0d.png)

I tried to follow the instruction: Run C/C++: Change Configuration Provider command and choose Makefile Tools from the list, however, when I run the command the only option I get from the list is "none".

**Comment by andreeis** [comment] 2022-08-04 22:27
@George-Gi, let's try the following steps to find the root of the problem.

1. In the folder where the extension is broken, set "makefile.logginLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log", reload the project, for a configure via the command "Makefile: Configure" in the pallette and share with us the files .vscode/dryrun.log and .vscode/extension.log and any makefile relevant settings you write in .vscode/settings.json. If there's any sensitive information, just replace with some dummy but similar content. Running that command forces the extension to activate even if in the beginning it decided not to and the logging may give us relevant information about what it doesn't find.
2. In the broken folder, run from the pallette the command "Makefile: Reset the Makefile Tools Extension workspace state (for troubleshooting)" and see whether the extension activates as in the beginning.

**Comment by George-Gi** [comment] 2022-08-29 10:19
So, I tried the suggestions in the broken folder. One thing to mention is that I don't see in the .vscode/dryrun.log. I need to highlight that the broken folder includes another folder, which has .vscode folder as well (in case this plays a role).

1. Indeed with the "Makefile: Configure" the extension shows up. I paste below part of the extension.log, as it has repeating information for a lot of files of my project.

> Configurations cached at c:\Users\UserName\AppData\Roaming\Code\User\workspaceStorage\3a9c0ad8442761b192ed93305de5dea2\ms-vscode.makefile-tools\configurationCache.log
Always pre-configure: false
Dry-run switches: --always-make,--keep-going,--print-directory
Additional compiler names: 
Exclude compiler names: 
No current configuration is defined in the workspace state. Assuming 'Default'.
Reading current build target "all" from the workspace state.
No current launch configuration is set in the workspace state.
Default launch configuration: MIMode = undefined,
                    miDebuggerPath = undefined,
                    stopAtEntry = undefined,
                    symbolSearchPath = undefined
Configure on open: true
Configure on edit: true
Configure after command: true
Only .PHONY targets: false
Save before build or configure: true
Build before launch: true
Clear output before build: true
Ignore directory commands: true
compile_commands.json path: null
Deduced command 'C:\Program Files (x86)\Atmel\Studio\7.0\shellutils\make.exe -f C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug\Makefile -C C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug' for configuration "Default"
Saving opened files before build.
Configuring from cache: c:\Users\UserName\AppData\Roaming\Code\User\workspaceStorage\3a9c0ad8442761b192ed93305de5dea2\ms-vscode.makefile-tools\configurationCache.log
Load configuration from cache elapsed time: 0.04
Sending Workspace Browse Configuration: -----------------------------------
    Browse Path: "Various Paths"
    Standard: undefined
    Compiler Path: undefined
    Compiler Arguments: "Various args"

> Sending configuration (from cache) for file c:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\atmel_start.c -----------------------------------
    Defines: __SAME70Q21B__;DEBUG
    Includes: "Various Paths"
    Force Includes: 
    Standard: gnu99
    IntelliSense Mode: undefined
    Compiler Path: C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\arm\arm-gnu-toolchain\bin\arm-none-eabi-gcc.exe
    Compiler Arguments: "Various args"

> Parsing for IntelliSense elapsed time: 18.442
Parsing for launch targets.
Analyzing line: make: Entering directory "Various file paths and flags"
Producing target binary: DSM_MkII_Probe_MCU.elf
Adding launch configuration:
C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug>DSM_MkII_Probe_MCU.elf()
Analyzing line: make: Leaving directory 'C:/Users/UserName/Development/DSM_MkII_Probe/DSM_MkII_Probe_MCU/Debug'
POPD command or end of MAKE -C: leaving directory C:/Users/UserName/Development/DSM_MkII_Probe/DSM_MkII_Probe_MCU/Debug and entering directory c:\Users\UserName\Development\DSM_MkII_Probe
Analyzing line: make: Entering directory 'C:/Users/UserName/Development/DSM_MkII_Probe/DSM_MkII_Probe_MCU/Debug'
MAKE -C: entering directory C:/Users/UserName/Development/DSM_MkII_Probe/DSM_MkII_Probe_MCU/Debug
Analyzing line: make: Leaving directory 'C:/Users/UserName/Development/DSM_MkII_Probe/DSM_MkII_Probe_MCU/Debug'
POPD command or end of MAKE -C: leaving directory C:/Users/UserName/Development/DSM_MkII_Probe/DSM_MkII_Probe_MCU/Debug and entering directory c:\Users\UserName\Development\DSM_MkII_Probe
Found the following 1 launch targets defined in the makefile: C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug>DSM_MkII_Probe_MCU.elf()
Complete list of launch targets: C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug>DSM_MkII_Probe_MCU.elf()
Parsing for launch targets elapsed time: 0.182
Generating parse content for build targets.
Generating targets information with command: 'C:\Program Files (x86)\Atmel\Studio\7.0\shellutils\make.exe all -f C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug\Makefile -C C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug --print-data-base --no-builtin-variables --no-builtin-rules --question'
Writing the dry-run output: c:\Users\UserName\AppData\Roaming\Code\User\workspaceStorage\3a9c0ad8442761b192ed93305de5dea2\ms-vscode.makefile-tools\targets.log
Spawning child process with:
 process name: "C:\Program Files (x86)\Atmel\Studio\7.0\shellutils\make.exe"
 process args: all,-f,C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug\Makefile,-C,C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug,--print-data-base,--no-builtin-variables,--no-builtin-rules,--question
 working directory: c:\Users\UserName\Development\DSM_MkII_Probe
 shell type: default
Generating dry-run elapsed time: 0.328
Parsing for build targets from: "c:\Users\UserName\AppData\Roaming\Code\User\workspaceStorage\3a9c0ad8442761b192ed93305de5dea2\ms-vscode.makefile-tools\targets.log"
Found the following 600 build targets defined in the makefile: "Various paths"
Parsing build targets elapsed time: 0.02
Configure finished. The status for all the subphases that ran:
loadFromCache: return code = 0, elapsed time = 0.04
generateParseContent: return code = 0, elapsed time = 0.984
preprocessParseContent: return code = 0, elapsed time = 0
parseIntelliSense: return code = 0, elapsed time = 18.442
parseLaunch: return code = 0, elapsed time = 0.182
dryrunTargets: return code = 0, elapsed time = 0.328
parseTargets: return code = 0, elapsed time = 0.02
Configure succeeded.
Sending telemetry: eventName = configure
properties: firstTime = "false",makeDryRun = "true",readCache = "true",isClean = "true",processTargetsSeparately = "false",resetBuildTarget = "false",triggeredBy = "configure dirty (on open), settings (configureOnOpen)",buildTarget = "all"
measures: numberBuildTargets = "600",numberLaunchTargets = "1",numberIndexedSourceFiles = "173",numberMakefileConfigurations = "0",totalElapsedTime = "23.167",exitCode = "0",loadFromCache.exitCode = "0",loadFromCache.elapsed = "0.04",generateParseContent.exitCode = "0",generateParseContent.elapsed = "0.984",preprocessParseContent.exitCode = "0",preprocessParseContent.elapsed = "0",parseIntelliSense.exitCode = "0",parseIntelliSense.elapsed = "18.442",parseLaunch.exitCode = "0",parseLaunch.elapsed = "0.182",dryrunTargets.exitCode = "0",dryrunTargets.elapsed = "0.328",parseTargets.exitCode = "0",parseTargets.elapsed = "0.02"
Configure elapsed time: 23.167
Sending telemetry: eventName = settings
properties: makefile.loggingLevel = "Debug",makefile.makePath = "...",makefile.makeDirectory = "...",makefile.makefilePath = "...",makefile.extensionLog = "..."
Saving opened files before build.
Loading configurations from cache is not necessary.
Generating configuration cache with command: 'C:\Program Files (x86)\Atmel\Studio\7.0\shellutils\make.exe all -f C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug\Makefile -C C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug --dry-run --keep-going --print-directory'
Writing the dry-run output: c:\Users\UserName\AppData\Roaming\Code\User\workspaceStorage\3a9c0ad8442761b192ed93305de5dea2\ms-vscode.makefile-tools\dryrun.log
Spawning child process with:
 process name: "C:\Program Files (x86)\Atmel\Studio\7.0\shellutils\make.exe"
 process args: all,-f,C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug\Makefile,-C,C:\Users\UserName\Development\DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug,--dry-run,--keep-going,--print-directory
 working directory: c:\Users\UserName\Development\DSM_MkII_Probe
 shell type: default
Generating dry-run elapsed time: 0.929
Preprocessing: "c:\Users\UserName\AppData\Roaming\Code\User\workspaceStorage\3a9c0ad8442761b192ed93305de5dea2\ms-vscode.makefile-tools\dryrun.log"
Preprocess elapsed time: 0
Parsing for IntelliSense.
Updating the CppTools IntelliSense Configuration Provider.
Parsing dry-run output for CppTools Custom Configuration Provider.
Analyzing line: make: Entering directory 'C:/Users/UserName/Development/DSM_MkII_Probe/DSM_MkII_Probe_MCU/Debug'
MAKE -C: entering directory C:/Users/UserName/Development/DSM_MkII_Probe/DSM_MkII_Probe_MCU/Debug
Analyzing line: make: Leaving directory 'C:/Users/UserName/Development/DSM_MkII_Probe/DSM_MkII_Probe_MCU/Debug'
POPD command or end of MAKE -C: leaving directory C:/Users/UserName/Development/DSM_MkII_Probe/DSM_MkII_Probe_MCU/Debug and entering directory c:\Users\UserName\Development\DSM_MkII_Probe
Sending Workspace Browse Configuration: -----------------------------------
    Browse Path: "Various Paths"
    Standard: undefined
    Compiler Path: undefined
    Compiler Arguments: "Various args"


In settings.json:
```
"makefile.launchConfigurations": [
        {
            "cwd": "C:\\Users\\UserName\\Development\\DSM_MkII_Probe\\DSM_MkII_Probe_MCU\\Debug",
            "binaryPath": "C:\\Users\\UserName\\Development\\DSM_MkII_Probe\\DSM_MkII_Probe_MCU\\Debug\\DSM_MkII_Probe_MCU.elf",
            "binaryArgs": []
        }
    ]
```

2. I executed the suggested command, but the extension doesn't get activated.

**Comment by andreeis** [comment] 2022-08-29 21:15
You have no "makefile.configurations" setting? The "makefile.launchConfigurations" is for later, after we figure out the activation, IntelliSense works, you also build...etc...
Also, you didn't include any of "makefile.makefilePath" or "makefile.makeDirectory" in your latest reply, how you are setting those?

Is the main entrypoint makefile at DSM_MkII_Probe\DSM_MkII_Probe_MCU\Debug\Makefile?
Do you set "makefilePath" and/or "makeDirectory" somewhere in some settings.json?
Do you load in VSCode the folder at DSM_MkII_Probe\DSM_MkII_Probe_MCU? Does this have a ".vscode" subfolder without dryrun.log? What is the subfolder with another ".vscode" which has a dryrun.log?

**Comment by George-Gi** [comment] 2023-02-06 09:11
Quite late reply on this, since I had to push it back due to priorities.
I picked it up again end the results:

```
"makefile.makeDirectory": "DSM_MkII_Probe_MCU\\Debug",
"makefile.makefilePath": "DSM_MkII_Probe_MCU\\Debug\\Makefile",
"makefile.makePath": "C:\\Program Files (x86)\\Atmel\\Studio\\7.0\\shellutils\\make"
```

are placed in the settings.json. I figured out that if I use ```${workspaceFolder}``` to set the path in these fields, the ```${workspaceFolder}``` is not parsed, and is just replaced with the literal and not the workspace folder.
If I completely remove ```${workspaceFolder}``` and just write the relative path (as I pasted them above) it works.
However, every time I open vscode I need to manually do ```Makefile: Configure```, otherwise the Makefile extension icon doesn't appear.

Also, I tried:
```
    "makefile.configurations": [
        {
            "name": "myconf",
            "buildLog": "",
            "makeArgs": [],
            "makeDirectory": "DSM_MkII_Probe_MCU\\Debug",
            "makefilePath": "DSM_MkII_Probe_MCU\\Debug\\Makefile",
            "makePath": "C:\\Program Files (x86)\\Atmel\\Studio\\7.0\\shellutils\\make.exe",
            "loggingLevel": "Debug",
            "extensionLog": ".vscode/extension.log",
        }
    ],
```

but it complaints that it can't find an entry point.

and the dry run results of configuring with ``` "makefile.configurations"```:
```
make.exe --dry-run --keep-going --print-directory
'make.exe' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by andreeis** [comment] 2023-02-08 18:57
@George-Gi , ${workspaceFolder} expansion will work soon, it's our next work item to implement for the 0.7 release.
Regarding using "makefile.configurations" setting, are you also chosing the "myconf" in the left UI, specifically the "Configuration" control? Any setting defined in "makefile.configurations[].*" won't take effect until you select that name in the UI instead of the "Default".

**Comment by George-Gi** [comment] 2023-02-09 08:21
The thing is that the icon on the left is not shown if I don't do ```Makefile: Configure```. And when I use the ```makefile.configurations``` when I try to do  ```Makefile: Configure```, it gives the error I mentioned above.

**Comment by andreeis** [comment] 2023-02-13 18:13
@George-Gi , several more questions to gather more data. Just in case we may have a bug related to adding or not the ".exe" extension to "makePath": if you add ".exe" to the global "makePath" setting does it stop working? If you remove ".exe" from the "makefile.configurations[].makePath" setting does it work? That is one difference I notice between the two cases.

Do you still have another folder with identical settings and structure that you open in VSCode and the extension activates automatically (without you having to run manually the configure command) and you see the Makefile Tools UI left panel? Asking because I read the older history of this issue.

For now, it's a total mystery why you don't see the "C/C++" icon on the left unless you run the configure command manually. The extension is supposed to activate when a makefile is present anywhere inside the folder that is opened in VSCode, then it's true that we hide the UI if we don't find a makefile in the root or at the "makefile.makefilePath" setting but in your case we should find it (otherwise the manual configure would fail), so we should show it.

So 2 problems here for now, having the manual configure find "make.exe" when using "makefile.configurations[].makePath" and not fail. Then get the left UI show up from the beginning and not need a manual configure at all to enable the UI.

**Comment by George-Gi** [comment] 2023-02-21 07:26
If I suffix with .exe the path in the global "makePath", it still works.

If I remove the trailing .exe from "makefile.configurations" it works.

The Icon still doesn't show up automatically though.
Yes, I tried the subfolder that has its own .vscode folder and settings, and for that one it automatically shows.

**Comment by andreeis** [comment] 2023-03-09 09:19
@George-Gi, I still didn't figure out the mystery of why the UI is not showing up for you when you first open your project but then, without any change, it does after you run configure (unless "makefile.makefilePath" points outside of your workspace, but it doesn't, correct?)
We made several changes of design around when the UI is shown and how we allow activation to finish or when we inhibit it... I'll share soon a private vsix for you to try (in case you have time before 0.7 will be out) to confirm whether it happens that the scenario is fixed now.
Also, are you using "open folder" or "add folder" to an existing workspace?

**Comment by George-Gi** [comment] 2023-04-03 07:16
> I still didn't figure out the mystery of why the UI is not showing up for you when you first open your project but then, without any change, it does after you run configure (unless "makefile.makefilePath" points outside of your workspace, but it doesn't, correct?)

Correct and correct.

I will better wait for the next release to check if the issue is fixed.

I use "open folder".

**Comment by andreeis** [comment] 2023-07-11 09:23
@George-Gi , I am closing this ticket for now but please reactivate if this problem still reproduces with the latest release Makefile Tools 0.7.0?

**Closed by andreeis** 2023-07-11 09:23 UTC
Labels: more info needed
