### ISSUE TITLE
include errors detected based on information provided by the configurationProvider setting. (C/C++ 1696)

### ISSUE THREAD

**Issue by asdaqsamir** [microsoft/vscode-makefile-tools#444] opened 2023-03-24 17:24 UTC
I am able to build the makefile project fine using makefile extension but for some reason the includes are not being found by vscode.

My settings.json file looks like the following:

```
{
    "makefile.makeDirectory": "build",
    "makefile.makefilePath": "build/makefile_gcc_4.8.2_x86-64.mk",
    "makefile.makePath": "C:/ivy/keypad/lib/make/bin/make.exe",
    "makefile.configurations": [
        {
            "name": "Default",
            "makeArgs": [
                "-j",
                "15",
                "-O"
            ]
        }
    ],
    "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools"
}
```

See the image below for errors:
![image](https://user-images.githubusercontent.com/20444344/227597834-4621ba8f-676c-4ceb-81d6-b90a36e9976d.png)

_Originally posted by @github-actions[bot] in https://github.com/microsoft/vscode-cpptools/issues/8797#issuecomment-1110883177_

**Comment by andreeis** [comment] 2023-03-24 18:56
@asdaqsamir , please set in your .vscode/settings.json:

"makefile.loggingLevel": "Debug",
"makefile.extensionOutputFolder": "./MyOutputFolder" (or wherever you want us to create a folder or point to an existing folder where we can drop some files without causing you any inconvenience),
"makefile.extensionLog": "extension.log"

Then reopen your project in VSCode, let the extension configure process finish (you can watch in the Makefile Tools output channel that logging stops and there is a "Configure finished" or similar message) then share with us these files from MyOutputFolder: dryrun.log and extension.log

Additionally, you can open the .c file in your screenshot, then run the command "C/C++ diagnostics" from the palette and share with us the text in the "C/C++ Diagnostics" output channel.

I see your "Default" configuration defined in settings.json and I assume you also selected it in the "C/C++" left panel UI (via the edit pen to the right of "Configuration" UI element).

**Comment by asdaqsamir** [comment] 2023-03-24 19:40
My settings.json looks like this now:
```
{
    "makefile.loggingLevel": "Debug",
    "makefile.extensionOutputFolder": "build",
    "makefile.extensionLog": "extension.log",
    "makefile.makeDirectory": "build",
    "makefile.makefilePath": "build/makefile_gcc_4.8.2_x86-64.mk",
    "makefile.makePath": "C:/ivy/keypad/lib/make/bin/make.exe",
    "makefile.configurations": [
        {
            "name": "Default",
            "makeArgs": [
                "-j",
                "15",
                "-O"
            ]
        }
    ],
    "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools"
}
```
See attached for extesion.log, dryrun.log, configurationCache.log and targets.log.


Following output is by running the "C/C++ Log diagnostics"

```
-------- Diagnostics - 3/24/2023, 2:35:25 PM
Version: 1.14.5
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "c:\\ivy\\keypad\\lib\\lib_cml\\asset\\feature\\keypad\\v00/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplici
[configurationCache.log](https://github.com/microsoft/vscode-makefile-tools/files/11066033/configurationCache.log)
[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/11066034/dryrun.log)
[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/11066035/extension.log)
[targets.log](https://github.com/microsoft/vscode-makefile-tools/files/11066036/targets.log)
t": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPath": "cl.exe",
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.makefile-tools",
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "${workspaceFolder}/**"
        ]
    }
}
Custom browse configuration: 
{
    "browsePath": []
}
Custom configurations:
[ C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\src\cml_keypad_indicator_group.c ]
{
    "defines": [
        "HAL_XLCAN",
        "NDEBUG",
        "MODULE_PLATFORM_AR",
        "A6MX"
    ],
    "includePath": [],
    "forcedInclude": [],
    "compilerPath": "c:\\ivy\\keypad\\lib\\lib_oel\\environment\\mingw\\bin\\x86_64-w64-mingw32-gcc.exe",
    "compilerArgs": [
        "-B",
        "../../../../../..\\lib_oel\\environment\\mingw\\bin",
        "-g3",
        "-Wpacked",
        "-Wno-unknown-pragmas",
        "-Wall",
        "-fno-peephole",
        "-fshort-enums",
        "-funsigned-char",
        "-c",
        "-o",
        "do_tgt_gcc_4.8.2_x86-64/cml_keypad_indicator_group.o",
        "../src/cml_keypad_indicator_group.c"
    ]
}
Translation Unit Mappings:
[ C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\src\cml_keypad_indicator_group.c ]:
    C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\src\cml_keypad_indicator_group.c
Translation Unit Configurations:
[ C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\src\cml_keypad_indicator_group.c ]:
    Process ID: 20940
    Memory Usage: 46 MB
    Compiler Path: C:\ivy\keypad\lib\lib_oel\environment\mingw\bin\x86_64-w64-mingw32-gcc.exe
    Includes:
        C:\ivy\keypad\lib\lib_oel\environment\mingw\lib64\gcc\x86_64-w64-mingw32\4.8.3\include
        C:\ivy\keypad\lib\lib_oel\environment\mingw\lib64\gcc\x86_64-w64-mingw32\4.8.3\include-fixed
        C:\ivy\keypad\lib\lib_oel\environment\mingw\x86_64-w64-mingw32\include
    Defines:
        HAL_XLCAN
        NDEBUG
        MODULE_PLATFORM_AR
        A6MX
    Standard Version: c11
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=40803
Total Memory Usage: 46 MB

```

**Comment by sean-mcmanus** [comment] 2023-03-24 19:48
The `"includePath": [],` indicates the C/C++ extension isn't being sent the includePath. One potential workaround would be to add `"mergeConfigurations": true` and a manually configured `"includePath": []` and remove the defines from `"defines": []` in c_cpp_properties.json.

**Comment by asdaqsamir** [comment] 2023-03-25 12:37
The project has been setup in this way:


build: contains all the makefiles that are needed to build the makefile project
- makefile_gcc_4.8.2_x86-64.mk
- lib.mk
- includes.mk


Note that most of the makefile is stitched together in $(VOB_ROOT)/lib_machine/tools/makefile/makefile_sim_win64.mk which is added at the end of makefile_gcc_4.8.2_x86-64.mk for compiling within a common makefile architecture. In this makeflile, all the includes come together using the variables INC_PATHS_INT and INC_PATHS_EXT.

 You can see all the files in the pic below:
![image](https://user-images.githubusercontent.com/20444344/227717612-ed8bcd96-30ba-4314-8274-af08ad94c500.png)

**Comment by asdaqsamir** [comment] 2023-03-25 13:34
@sean-mcmanus I tried the workaround, it takes care of the problems previously reported and I can go to definition of the included header files, however I am unable to use certain functionality when I right click. For example, clicking on "Switch Header/Source" does not work. 

c_cpp_properties.json looks like this now:
```
{
    "configurations": [
        {
            "name": "Default",
            "includePath": [
                "include",
                "../../../../../lib_cml/asset/base/v00/include",
                "../../../../../lib_cml/asset/interface/v00/include",
                "../../../../../lib_oel/oel/include",
                "../../../../../lib_oel/oel/include_oeluk",
                "../../../../../lib_a4/scl/include",
                "../../../../../lib_a4/hal/include",
                "../../../../../lib_standards/c/include"
            ],
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}
```

and the "C/C++ Diagnostic Log" looks like this:
```
-------- Diagnostics - 3/25/2023, 8:30:42 AM
Version: 1.14.5
Current Configuration:
{
    "name": "Default",
    "includePath": [
        "c:\\ivy\\keypad\\lib\\lib_cml\\asset\\feature\\keypad\\v00\\include",
        "c:\\ivy\\keypad\\lib\\lib_cml\\asset\\base\\v00\\include",
        "c:\\ivy\\keypad\\lib\\lib_cml\\asset\\interface\\v00\\include",
        "c:\\ivy\\keypad\\lib\\lib_oel\\oel\\include",
        "c:\\ivy\\keypad\\lib\\lib_oel\\oel\\include_oeluk",
        "c:\\ivy\\keypad\\lib\\lib_a4\\scl\\include",
        "c:\\ivy\\keypad\\lib\\lib_a4\\hal\\include",
        "c:\\ivy\\keypad\\lib\\lib_standards\\c\\include"
    ],
    "configurationProvider": "ms-vscode.makefile-tools",
    "compilerPathIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "intelliSenseModeIsExplicit": false,
    "macFrameworkPath": [],
    "windowsSdkVersion": "10.0.19041.0",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "mergeConfigurations": true,
    "compilerPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe",
    "browse": {
        "path": [
            "include",
            "../../../../../lib_cml/asset/base/v00/include",
            "../../../../../lib_cml/asset/interface/v00/include",
            "../../../../../lib_oel/oel/include",
            "../../../../../lib_oel/oel/include_oeluk",
            "../../../../../lib_a4/scl/include",
            "../../../../../lib_a4/hal/include",
            "../../../../../lib_standards/c/include",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": []
}
Translation Unit Mappings:
[ C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\src\cml_keypad_comm_mngr.c ]:
    C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\src\cml_keypad_comm_mngr.c
[ C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\src\cml_keypad_indicator_group.c ]:
    C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\src\cml_keypad_indicator_group.c
Translation Unit Configurations:
[ C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\src\cml_keypad_comm_mngr.c ]:
    Process ID: 15576
    Memory Usage: 57 MB
    Compiler Path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe
    Includes:
        C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\include
        C:\ivy\keypad\lib\lib_cml\asset\base\v00\include
        C:\ivy\keypad\lib\lib_cml\asset\interface\v00\include
        C:\ivy\keypad\lib\lib_oel\oel\include
        C:\ivy\keypad\lib\lib_oel\oel\include_oeluk
        C:\ivy\keypad\lib\lib_a4\scl\include
        C:\ivy\keypad\lib\lib_a4\hal\include
        C:\ivy\keypad\lib\lib_standards\c\include
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\atlmfc\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt
    Standard Version: ms_c17
    IntelliSense Mode: windows-msvc-x64
[ C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\src\cml_keypad_indicator_group.c ]:
    Process ID: 2064
    Memory Usage: 56 MB
    Compiler Path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe
    Includes:
        C:\ivy\keypad\lib\lib_cml\asset\feature\keypad\v00\include
        C:\ivy\keypad\lib\lib_cml\asset\base\v00\include
        C:\ivy\keypad\lib\lib_cml\asset\interface\v00\include
        C:\ivy\keypad\lib\lib_oel\oel\include
        C:\ivy\keypad\lib\lib_oel\oel\include_oeluk
        C:\ivy\keypad\lib\lib_a4\scl\include
        C:\ivy\keypad\lib\lib_a4\hal\include
        C:\ivy\keypad\lib\lib_standards\c\include
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\atlmfc\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt
    Standard Version: ms_c17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 113 MB
```

Also note that this error still shows up in the Output tab of vscode:
```
Error: the task 'makefile: Makefile Tools Build Task' neither specifies a command nor a dependsOn property. The task will be ignored. Its definition is:
{
    "type": "shell",
    "id": "shell,C:\\ivy\\keypad\\lib\\make\\bin\\make.exe,-f,c:\\ivy\\keypad\\lib\\lib_cml\\asset\\feature\\keypad\\v00\\build\\makefile_gcc_4.8.2_x86-64.mk,-C,c:\\ivy\\keypad\\lib\\lib_cml\\asset\\feature\\keypad\\v00\\build,-j,15,-O,",
    "problemMatcher": [],
    "label": "makefile: Makefile Tools Build Task"
}
```

**Comment by asdaqsamir** [comment] 2023-03-25 13:53
I just wanted to thank you for all your help with this issue.

A side question, in "C/C++ Diagnostic Log" why does it show properties of windows compiler even though I am using gcc as the compiler in the makefile make path? The log above shows Visual Studio 2019 Professional includes and compiler paths.

**Comment by andreeis** [comment] 2023-03-26 20:13
@asdaqsamir , currently the extension parses only "make --dry-run" output log and finds only paths given to /I /FI compiler switches. We have a work item to include things given via the "INCLUDE" environment variable (which the microsoft MSVC toolset like cl.exe uses). I can't find the GitHub issue now to reference it. Until I find it, I will use this issue you opened (which otherwise I would have closed it as by design). We can add your variables to it (or add a setting for users to mention that it represents an INCLUDE environment variable setting). We don't know when we can get to implement this support (parse include paths from key environment variables but we will triage soon and let you know).

The error in the tasks output channel is something new, not caused by us, I opened a work item towards the VSCode team: https://github.com/microsoft/vscode/issues/176670. 

@sean-mcmanus I'll let you answer the last question about compiler gcc and diagnostics log.

**Comment by asdaqsamir** [comment] 2023-03-27 13:50
@andreeis thank you for considering this as a feature but I think these are make variables and not environment variables. I am sure it will help others out there, I did a quick search on google for "how to add include path to makefile" and the first link is to this https://stackoverflow.com/questions/4134764/how-to-define-several-include-path-in-makefile (posted 12 years ago) and many upvotes. In summary, following are three possible solutions using make variables:

```
INC=$(DIR1) $(DIR2) ...
INC_PARAMS=$(foreach d, $(INC), -I$d)
or
INC_PARAMS=$(INC:%=-I%)
or
INC_PARAMS = $(addprefix -I,$(INC))
```

I think we are using the last one of the three using `addprefix`.

**Comment by sean-mcmanus** [comment] 2023-03-27 17:54
I'm referring to the logging from comment https://github.com/microsoft/vscode-makefile-tools/issues/444#issuecomment-1483825930, which has no configuration provider info being sent for some reason. I don't see the compiler path logging you're referring to, but if it shows the compiler path is being sent with the custom configuration then then it should be using that instead of cl.exe.

**Closed** 2023-07-11 08:38 UTC
Labels: more info needed
