### ISSUE TITLE
parseCompilerArgs.sh - Unterminated quoted string for automake generated Makefile due to use of line continuation backslash

### ISSUE THREAD

**Issue by wsfulton** [microsoft/vscode-makefile-tools#628] opened 2024-07-27 16:05 UTC
Using Makefile Tools version 0.10.16 prerelease version as well as 0.9.10 release.

Whatever chunks up dryrun.log into regions, probably needs to filter out line continuation backslash characters at the end of the string passed to parseCompilerArgs.sh or maybe join up with the next line/region.

This is the error message:
```
Preprocessing: "/home/william/.vscode-server/data/User/workspaceStorage/b406400708bbea2df76e2fb270c1ce86/ms-vscode.makefile-tools/dryrun.log"
Preprocess elapsed time: 0
Parsing for IntelliSense.
Updating the CppTools IntelliSense Configuration Provider.
Parsing dry-run output for CppTools Custom Configuration Provider.
Error running the compiler args parser script /home/william/.vscode-server/extensions/ms-vscode.makefile-tools-0.10.16/assets/parseCompilerArgs.sh for regions (   -g -Wall -W -pedantic -MT CParse/cscanner.o -MD -MP -c -o CParse/cscanner.o CParse/cscanner.c &&\): /bin/sh: 1: Syntax error: Unterminated quoted string

The compiler args parser script '/home/william/.vscode-server/extensions/ms-vscode.makefile-tools-0.10.16/assets/parseCompilerArgs.sh' failed with error code    -g -Wall -W -pedantic -MT CParse/cscanner.o -MD -MP -c -o CParse/cscanner.o CParse/cscanner.c &&\ for regions (undefined)
Sending configuration for file /home/william/swig/github/swig/Source/CParse/cscanner.c -----------------------------------
```

Relevant line from dryun.log:
```
depbase=`echo CParse/cscanner.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H   -I../Source/Include -I../Source/CParse -I../Source/Include -I../Source/DOH -I../Source/CParse -I../Source/Doxygen -I../Source/Preprocessor -I../Source/Swig -I../Source/Modules   -g -Wall -W -pedantic -MT CParse/cscanner.o -MD -MP -MF $depbase.Tpo -c -o CParse/cscanner.o CParse/cscanner.c &&\
mv -f $depbase.Tpo $depbase.Po
```

Relevant snippet from Makefile:
```makefile
.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
```

Joining the lines instead of using a line continuation backslash does work around the problem:
```makefile
.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< && $(am__mv) $$depbase.Tpo $$depbase.Po
```

However, the Makefile is generated by automake, so not a workable solution.

**Comment by gcampbell-msft** [comment] 2024-07-29 13:00
@wsfulton Thanks for creating the issue and letting us know. 

Before taking time to investigate, I'm curious if this is also happening in official release versions prior to 0.9.10? I'm just trying to get an understanding if this is a general bug, or if it was introduced in the past 2 versions. Thanks!

**Comment by wsfulton** [comment] 2024-07-30 05:40
Version 0.8.22:
```
Error while running the compiler args parser script '/home/william/.vscode-server/extensions/ms-vscode.makefile-tools-0.8.22/assets/parseCompilerArgs.sh' for regions ("   -g -Wall -W -pedantic -MT CParse/cscanner.o -MD -MP -c -o CParse/cscanner.o CParse/cscanner.c &&\)": "/bin/sh: 1: Syntax error: Unterminated quoted string
"
The compiler args parser script '/home/william/.vscode-server/extensions/ms-vscode.makefile-tools-0.8.22/assets/parseCompilerArgs.sh' failed with error code 2 for regions (   -g -Wall -W -pedantic -MT CParse/cscanner.o -MD -MP -c -o CParse/cscanner.o CParse/cscanner.c &&\)
Sending configuration for file /home/william/swig/github/swig/Source/CParse/cscanner.c -----------------------------------
```
Version 0.7:
```
Error while running the compiler args parser script '/tmp/parseCompilerArgs.sh' for regions ("   -g -Wall -W -pedantic -MT CParse/cscanner.o -MD -MP -c -o CParse/cscanner.o CParse/cscanner.c &&\)": "/bin/sh: 1: Syntax error: Unterminated quoted string
"
The compiler args parser script '/tmp/parseCompilerArgs.sh' failed with error code 2 for regions (   -g -Wall -W -pedantic -MT CParse/cscanner.o -MD -MP -c -o CParse/cscanner.o CParse/cscanner.c &&\)
Sending configuration for file /home/william/swig/github/swig/Source/CParse/cscanner.c -----------------------------------
```
Version 0.6:
```
Error while running the compiler args parser script '/tmp/parseCompilerArgs.sh' for regions ("   -g -Wall -W -pedantic -MT CParse/cscanner.o -MD -MP -c -o CParse/cscanner.o CParse/cscanner.c &&\)": "/bin/sh: 1: Syntax error: Unterminated quoted string
"
The compiler args parser script '/tmp/parseCompilerArgs.sh' failed with error code 2 for regions (   -g -Wall -W -pedantic -MT CParse/cscanner.o -MD -MP -c -o CParse/cscanner.o CParse/cscanner.c &&\)
Sending configuration for file /home/william/swig/github/swig/Source/CParse/cscanner.c -----------------------------------
```
Incidentally, this is for the swig project, but first requires the Makefile.in modification in #98 in order to avoid an infinite loop when make is invoked with `make source --dry-run --always-make --keep-going --print-directory`.

**Comment by gcampbell-msft** [comment] 2024-07-30 14:43
@wsfulton Got it, so these seems like a general bug that has been present for a while and this issue has helped us find it. Thanks! I'll mark it as a bug and place it on the backlog, we will fix it as soon as we can based on bandwidth

**Comment by g2flyer** [comment] 2024-07-30 23:30
For what's worth, i incidentally also just ran over the same issue today with OFI's libfabric (https://github.com/ofiwg/libfabric.git )

**Comment by gcampbell-msft** [comment] 2024-10-02 18:00
@wsfulton @g2flyer Could you all test the following vsix and see if it resolves this issue for you? 

[makefile-tools.zip](https://github.com/user-attachments/files/17234168/makefile-tools.zip)

You'll need to download the zip file, change the extension to .vsix, and then you'll need to install it into VS Code manually to test. Thanks!

**Comment by g2flyer** [comment] 2024-10-11 00:25
> [@wsfulton](https://github.com/wsfulton) [@g2flyer](https://github.com/g2flyer) Could you all test the following vsix and see if it resolves this issue for you?
> 
> [makefile-tools.zip](https://github.com/user-attachments/files/17234213/makefile-tools.zip)
> 
> You'll need to download the zip file, change the extension to .vsix, and then you'll need to install it into VS Code manually to test. Thanks!

still get the (seemingly identical) error 'ad ccharacters in variable name '' ... :-(

**Comment by gcampbell-msft** [comment] 2024-10-11 10:13
@g2flyer I'm not sure I understand the error you got, could you please add a screenshot with some context for the error message when it got output? Thanks!

**Comment by g2flyer** [comment] 2024-10-11 16:48
> [@g2flyer](https://github.com/g2flyer) I'm not sure I understand the error you got, could you please add a screenshot with some context for the error message when it got output? Thanks!

Ooops, the quoted error was actually due to a merge conflict i overlooked.  But after fixing that and rerunning the tests i still get the (real :-) old problem `parseCompilerArgs.sh for regions (   -Wall -O2 -pipe -fvisibility=hidden -Wall -Wundef -Wpointer-arith -MT util/info.o -MD -MP -c -o util/info.o util/info.c &&\): /bin/sh: 1: Syntax error: Unterminated quoted string`.  Thinking that actual text files are easier to analyze, i've created a zip file with the makefile tools output and the dryrun.log file for both the standard extension and above referenced manually installed extension: [makefile-tools-tests.zip](https://github.com/user-attachments/files/17345499/makefile-tools-tests.zip)

**Comment by gcampbell-msft** [comment] 2024-10-17 15:21
@g2flyer Ah, thanks for the follow up and the additional information, I think I've figured out what was happening, could you test this extension? 

[makefile-tools.zip](https://github.com/user-attachments/files/17415073/makefile-tools.zip)

**Comment by g2flyer** [comment] 2024-10-17 15:39
> [@g2flyer](https://github.com/g2flyer) Ah, thanks for the follow up and the additional information, I think I've figured out what was happening, could you test this extension?
> 
> [makefile-tools.zip](https://github.com/user-attachments/files/17415073/makefile-tools.zip)

i tried but didn't seem to work (i.e., no intellisense) :-( From log-files below it seems there is some issue with all the `undefined` and no real action shown.  One thing, though. Regardless on how i tried to configure (automatically after install, using Makefile: Clean Configure or Makefile: Reset (for troubleshooting)) it run for a long time with the pop-up 'Configuring from cache ...'.  I wonder whether the cache might be the problem but i couldn't quickly figure out on how to remove the cache ...
``` 
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
Yes
undefined
undefined
undefined'make --dry-run --always-make --keep-going --print-directory'
undefined
undefined
undefined
undefined
undefined
undefined
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
undefined
undefined
undefined
undefined
undefined
undefined
undefined'make all --print-data-base --no-builtin-variables --no-builtin-rules --question'
undefined
undefined
undefined
undefined
undefined
undefined
undefined
loadFromCache: undefined = 0, undefined = 0.02
generateParseContent: undefined = 0, undefined = 77.753
preprocessParseContent: undefined = 0, undefined = 0
parseIntelliSense: undefined = 0, undefined = 2.844
parseLaunch: undefined = 0, undefined = 0.226
dryrunTargets: undefined = 1, undefined = 0.129
parseTargets: undefined = 0, undefined = 0.065
undefined
undefined
Yes
undefined'make --dry-run --always-make --keep-going --print-directory'
undefined
undefined
undefined
undefined
undefined
undefined
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
Messages not found.
undefined
undefined
undefined
undefined
undefined
undefined
undefined'make all --print-data-base --no-builtin-variables --no-builtin-rules --question'
undefined
undefined
undefined
undefined
undefined
undefined
undefined
generateParseContent: undefined = 0, undefined = 75.888
preprocessParseContent: undefined = 0, undefined = 0
parseIntelliSense: undefined = 0, undefined = 2.911
parseLaunch: undefined = 0, undefined = 0.162
dryrunTargets: undefined = 1, undefined = 0.12
parseTargets: undefined = 0, undefined = 0.063
undefined
undefined

```

**Comment by g2flyer** [comment] 2024-10-17 16:30
> [@g2flyer](https://github.com/g2flyer) Hm, very interesting, when I tested with the dryrun log files that you sent, it seemed to work as expected.
> 
> UPDATE: I think I found the issue, here's the vsix: [makefile-tools.zip](https://github.com/user-attachments/files/17415833/makefile-tools.zip)
> 
> However, I don't expect that this will fix your issue. While it seems to better handle line continuation characters, it seems like there is still something going on with your dry-run file and with our parsing that is causing issues.
> 
> Please let me know if you can confirm my suspicions, and I can investigate further.

Yes, the new version returns to the log-files i got in the past. And yes, it didn't solve the problem but there was a subtle difference: Previously the error was
``` 
Error running the compiler args parser script /home/msteiner/.vscode-server/extensions/ms-vscode.makefile-tools-0.7.0/assets/parseCompilerArgs.sh for regions (   -Wall -O2 -pipe -fvisibility=hidden -Wall -Wundef -Wpointer-arith -MT util/info.o -MD -MP -c -o util/info.o util/info.c &&\): /bin/bash: -c: line 2: syntax error: unexpected end of file
```
while now it is
``` 
Error running the compiler args parser script /home/msteiner/.vscode-server/extensions/ms-vscode.makefile-tools-0.7.0/assets/parseCompilerArgs.sh for regions (   -Wall -O2 -pipe -fvisibility=hidden -Wall -Wundef -Wpointer-arith -MT util/info.o -MD -MP -c -o util/info.o util/info.c &&): /bin/bash: -c: line 2: syntax error: unexpected end of file
```
Note that the `\` disappeared.  So seems kindof as if in the processing the backslash was removed but not joined with following line (i.e., only \ was removed and not also newline?)

**Comment by gcampbell-msft** [comment] 2024-10-17 18:58
@g2flyer First, thanks for all of your help testing and being so quick to respond, it's very helpful and appreciated. 

That being said, I think I have some progress, could you try this? [makefile-tools.zip](https://github.com/user-attachments/files/17421211/makefile-tools.zip)

I still see an issue where some failures happen due to some command lines being too long, but I'm not sure there is much to be done about that, because that failure seems to be failing from the execution of the script itself and I'm not sure what control we can have of that. 

Thanks

**Comment by g2flyer** [comment] 2024-10-17 20:25
> [@g2flyer](https://github.com/g2flyer) First, thanks for all of your help testing and being so quick to respond, it's very helpful and appreciated.
> 
> That being said, I think I have some progress, could you try this? [makefile-tools.zip](https://github.com/user-attachments/files/17421211/makefile-tools.zip)
> 
> I still see an issue where some failures happen due to some command lines being too long, but I'm not sure there is much to be done about that, because that failure seems to be failing from the execution of the script itself and I'm not sure what control we can have of that.

With this version the parser error disappeared from the log, in the summary of the log there is a return code=1 from dryrunTargt.  Find attached that log-file plus the referenced one (where i couldn't find anything suspicious but maybe you can).[makefile-tools.v3.zip](https://github.com/user-attachments/files/17422510/makefile-tools.v3.zip)

BTW: if it help you for me to do additional investigations, run particular scripts or alike, just let me know.

**Comment by gcampbell-msft** [comment] 2024-10-17 20:45
@g2flyer Any additional information or investigation is always appreciated, I may not get to more investigation until tomorrow or after, but thanks for the feedback. 

It sounds like technically the original issue for this item is fixed, the line continuation is being handled. However, you're still hitting an issue?

For example, what's the specific issue you're still seeing and what's the outcome of the issue you're seeing? Are you not able to get intellisense? Etc. Thanks!

**Comment by g2flyer** [comment] 2024-10-17 21:08
> For example, what's the specific issue you're still seeing and what's the outcome of the issue you're seeing? Are you not able to get intellisense? Etc. Thanks!

Yep, no intellisense ...

**Comment by gcampbell-msft** [comment] 2024-10-18 17:40
@g2flyer I looked a little closer, and I believe I was correct in this comment: https://github.com/microsoft/vscode-makefile-tools/issues/628#issuecomment-2420309158. One of the lines in the dryrun.log is exceptionally long and therefore the script hits an error due to a command-line being much too long. 

I copied the specific lines that show the error in the output log below.
[error.log](https://github.com/user-attachments/files/17438787/error.log)

**Comment by g2flyer** [comment] 2024-10-18 19:07
> [@g2flyer](https://github.com/g2flyer) I looked a little closer, and I believe I was correct in this comment: [#628 (comment)](https://github.com/microsoft/vscode-makefile-tools/issues/628#issuecomment-2420309158). One of the lines in the dryrun.log is exceptionally long and therefore the script hits an error due to a command-line being much too long.
> 
> I copied the specific lines that show the error in the output log below. [error.log](https://github.com/user-attachments/files/17438787/error.log)

Ah, i see it there, although i cannot see that error in the three log-files i found and sent you: are there more log-files which i missed or is this visible only when running in debug mode or command-line or alike?  Actually, is there an (easy :-) way to run the processing on the command-line to be more easily able to debug?  Presumably it would be some invocation of `main.js` in some form?   Also, what is the maximum length supported?  With all the jsons main.js was not immediately digestable that i could find location.  Also thought first it would be a shell-limitation but if i run the compileArgsParse script it accepts these 315 char arguments ...

**Comment by gcampbell-msft** [comment] 2024-11-06 15:43
@g2flyer I just tested the repro that you sent by opening it up in WSL and I'm not reproducing the issue you describe. Because of this, I think that the PR #659 is ready to go in. However, if you are still facing the issues, then I definitely want to investigate them, and it would likely be best served by creating a new issue specific to the issue that you are still facing. 

When I tested the reproduction, I didn't see any error outputs in the Makefile output channel or the log. 

Could you possibly open a new issue for specifically the issue that you are still seeing? I understand it might be duplication, but since the referenced PR fixes the issue with the line continuation backslash, I plan to close this issue when it merges. Thanks!

**Closed** 2024-11-06 16:26 UTC
Labels: bug, Feature: Parsers

**Comment by gcampbell-msft** [comment] 2024-11-08 14:46
@g2flyer The PR #659 should be in the latest pre-release version 0.12.10. Thanks!
