### ISSUE TITLE
Compiler path sometimes not full path

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#316] opened 2022-05-02 22:10 UTC
Reported by @Lak4CYUT in issue https://github.com/microsoft/vscode-makefile-tools/issues/156.
For sensor.c, CppTools receives the compiler without a full path (as seen in C/C++ diagnostics logs). The Makefile Tools logs show that we always find the correct full path for the compiler.
We will try to reproduce this on our end and hopefully we'll find out where the full path is lost along the way.
Logs and details about repro (project on github and settings) in the 156 issue.

**Comment by Lak4CYUT** [comment] 2022-05-03 01:05
@andreeis 
Is there any way to configure 'compilerPath' manually? Maybe I can it as a workaround.

**Comment by gcampbell-msft** [comment] 2024-08-26 14:42
@Lak4CYUT Could you provide a repro project and steps to reproduce the bug that you're hitting? I'd like to see if I can diagnose or fix this for you, but reading through the linked bug @andreeis referenced, I'm not fully understanding the repro in order to test this. 

Thanks! We plan to close this in the next couple of weeks if we don't hear anything, so we'd love to get this information so that we can try to improve the extension.

**Comment by gcampbell-msft** [comment] 2024-10-02 17:41
I'm not able to reproduce this, closing as no repro.

**Closed by gcampbell-msft** 2024-10-02 17:41 UTC
Labels: bug, more info needed
