### ISSUE TITLE
Not all build targets listed

### ISSUE THREAD

**Issue by stryder-vtx** [microsoft/vscode-makefile-tools#182] opened 2021-06-11 23:03 UTC
1st a caveat: I'm completely new to vscode so I might've missed something here.

My Makefile has a section listing all the possible targets (for all) like:
```
PROGRAMS = \  
    bin/proga \   
    bin/progb \  
    bin/progc  

all: $(PROGRAMS) 
```
However, when I click the edit symbol to change the build target, all I get is:  
all
bin/proga
clean

so I can't select individual programs except the 1st one. Shouldn't it list all the targets?

**Comment by andreeis** [comment] 2021-06-16 21:51
I wrote by hand the pattern I saw above in one of my small programs and I didn't reproduce the problem. Then I copied exactly from what you wrote and no targets were parsed. I reviewed all differences and I started to see all targets being parsed again after I made sure that the "\" was the last character in the line. I couldn't reproduce exactly your scenario (I either had all 3 targets or none, you had just the first) but let's see if first we can unblock you. Remove any spaces after the "\" and let us know if you see all the targets being detected.
The extension is parsing these targets by running make with a few special switches and I compared how the make output looks for both cases and it looks that when "\" is followed by anything, make itself won't display these targets and even the PROGRAMS macro. So I think this would be a limitation of makefile syntax.
I am closing the report but reopen if you feel that this doesn't perfectly address your scenario.

**Closed by andreeis** 2021-06-16 21:51 UTC
