### ISSUE TITLE
Output window is opened whenever the extension processes changes to the makefile

### ISSUE THREAD

**Issue by dan1994** [microsoft/vscode-makefile-tools#115] opened 2021-02-19 15:12 UTC
First of all, this extension is awesome! I've been waiting for makefile support for some time now!

I've been tinkering with a sample project with a makefile and a single C++ source. What I've noticed is that whenever I update the makefile and then focus on the C++ file, the Makefile Tools output window is opened.
Is there a way to suppress this, as it is pretty annoying, especially when  simultaneously using the terminal (it switches from the terminal to the output window)?

**Comment by andreeis** [comment] 2021-02-19 16:16
Thank you for opening this report. We tried to tune the frequency with which the the extension shows the output window, not too often to be annoying but also to mark important moments in the project. This is good feedback and we can adjust at any time.
Our thought was that it would be useful to display the output window at the beginning of build, pre-configure and configure operations.
When you modify the makefile, you trigger an automatic re-configure of your project (because maybe the edits will translate into new switches, source files.... that would impact the IntelliSense) and this is a visibility trigger.

First, let us know what you think about this approach. Is this still too often? 

We can always add a setting to disable this, just in case.

What you can do now is to disable indirectly the output channel reveal by disabling automatic configures, with setting makefile.configureOnEdit as false. But remember to invoke the command makefile.configure (from the palette) every time you think you made a makefile edit that should change your IntelliSense state.

Let us know your thoughts about the visibility triggers and otherwise we'll still keep this work item opened and triage it because a new setting will not hurt.

**Comment by dan1994** [comment] 2021-02-19 16:29
Thanks for the quick reply!

My personal preference is to keep things in the background unless something goes wrong. In the ideal scenario I don't need to care when the extension is triggered nor what it does. All I want to care about is that the include directory or the new define I added are recognized by the intellisense. If something doesn't work I'll just open the output tab manually.

I do think that adding a setting to turn this off is enough, and will definitely resolve the issue as far as I'm concerned.

**Comment by andreeis** [comment] 2021-04-28 18:05
@dan1994, in the end we didn't add a new setting but we made the output channel to show only when there is an error.
Until we release Makefile Tools 0.2.1, if you want you can install this vsix to benefit of this change: https://github.com/microsoft/vscode-makefile-tools/actions/runs/793552744.

**Comment by dan1994** [comment] 2021-04-28 18:32
Thank you!

**Comment by COOLIRON2311** [comment] 2021-07-11 18:59
> @dan1994, in the end we didn't add a new setting but we made the output channel to show only when there is an error.
> Until we release Makefile Tools 0.2.1, if you want you can install this vsix to benefit of this change: https://github.com/microsoft/vscode-makefile-tools/actions/runs/793552744.

No you did not. The extension (0.2.2 on Ubuntu 20.04) opens Output tab each time the project containig makefile is opened even if the tab was disabled via terminal settings. Please, still consider adding an option to turn off the output completely.

**Comment by andreeis** [comment] 2021-07-14 00:04
Currently the output channel is shown when an error occurs, when the build starts and indeed at the beginning. We did not think that these few events may cause annoyance to any developer. I also missed the scenario of wanting the whole output tab missing form the UI (I wasn't aware of it). I just researched how to make that setting and we can make an easy fix for the extension to read the setting and always prevent output channel to appear.

Do you see the output channel for Makefile Tools being shown more often than what I am describing?

**Comment by COOLIRON2311** [comment] 2021-07-15 10:26
> Currently the output channel is shown when an error occurs, when the build starts and indeed at the beginning. We did not think that these few events may cause annoyance to any developer. I also missed the scenario of wanting the whole output tab missing form the UI (I wasn't aware of it). I just researched how to make that setting and we can make an easy fix for the extension to read the setting and always prevent output channel to appear.
> 
> Do you see the output channel for Makefile Tools being shown more often than what I am describing?

No, as you said, only at the beginning, on build and on error. It is the beginning part that causes the annoyance.

**Comment by mz8i** [comment] 2021-09-29 09:44
@andreeis I can confirm that this causes an annoyance - I am working on a monorepo where Make is responsible for just a small part of the project. I usually open the terminal right after opening VSCode, and having the terminal hijacked by Make output that is not relevant to my work 99% of the times, is annoying enough that it made me post here ;)

Introducing a switch would be desirable, but in fact I am wondering if it is useful for anyone, even people who use Make regularly, to draw the user's attention to the error-less output at the start of the extension.

In any case, I think the default behaviour should be not to force-show Make output at the start of the extension.

**Comment by andreeis** [comment] 2021-09-29 17:36
@mz8i and @COOLIRON2311, then it's time to add a setting. I thought, while we brainstormed with other users of this extension, that our new approach with showing the output window less was enough and a new setting was not needed.
I am reactivating this report and we will add the setting. Thank you for your feedback.

**Comment by andreeis** [comment] 2021-12-03 07:46
@mz8i, @COOLIRON2311, @dan1994, @Florin-Popescu, we released Makefile Tools 0.3.0 today which includes a bug fix for this problem. Let us know if you encounter any other issues.

If you would like, you can also leave us a review on [Market Place](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools&ssr=false#review-details).

**Closed by andreeis** 2021-12-03 07:46 UTC
