### ISSUE TITLE
No launch targets identified

### ISSUE THREAD

**Issue by MaddyGuthridge** [microsoft/vscode-makefile-tools#198] opened 2021-07-25 11:22 UTC
I'm trying to get my program to debug using this extension and I'm running into issues getting it to run with debugging.

This is the Makefile I'm using:

```
# Makefile for Assignment 2

CC = gcc
CFLAGS = -Wall -Werror -g

all: shuck

# Linking stage: turn all object files into one binary
shuck: shuck_core.o shuck_helpers.o shuck_builtins.o
	$(CC) $(CFLAGS) shuck_core.o shuck_helpers.o shuck_builtins.o -o shuck

# Shuck core: main function and starter code
shuck_core.o: shuck.c
	$(CC) $(CFLAGS) -c shuck.c -o shuck_core.o

# Shuck helpers: helper functions for managing IO
shuck_helpers.o: shuck_helpers.c
	$(CC) $(CFLAGS) -c shuck_helpers.c -o shuck_helpers.o

# Shuck builtins: functions built into the shell
shuck_builtins.o: shuck_builtins.c
	$(CC) $(CFLAGS) -c shuck_builtins.c -o shuck_builtins.o

# Remove all output files
clean:
	rm -rf shuck shuck_core.o shuck_builtins.o shuck_helpers.o

```

The extension correctly identifies all the build targets and will build correctly, but does not detect any launch targets. I have tried adding the launch targets manually with no success.
The binaries built with the extension work fine when invoked using the command line, so it's entirely an issue with the extension not recognising the output file.

Any fixes would be appreciated!

System: Ubuntu 20.04 WSL, Intel Core i7 10750H, 16 GB RAM

**Comment by MiguelGuthridge** [comment] 2021-07-25 14:02
It turns out that by adding them manually, it worked properly.

**Comment by andreeis** [comment] 2021-07-26 07:02
@MiguelGuthridge, thank you for creating this report. I am glad that you found how to manually specify launch targets in your .vscode/settings.json.
I am interested in analyzing your repro closer so that I understand why the extension did not detect any of the launch targets. It can be a bug (which we'd like to fix) or a limitation (if your build does not print any link commands for us to detect and parse).
Can you share your .vscode/dryrun.log and .vscode/extension.log, after setting "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log"?

**Comment by Kulmeetcodez** [comment] 2022-02-18 17:37
> It turns out that by adding them manually, it worked properly.

Can u please tell us how u did that

Thank you in advance!

**Comment by coriolus** [comment] 2022-02-23 15:21
Same problem here. All the build targets identified and built correctly, but no launch targets detected. Had to resort to manually  editing settings.json file like previouly suggested. Curious what is the cause and how it could be fixed.

**Comment by andreeis** [comment] 2022-02-24 10:50
@coriolus, as I described in my reply above, you can:

> Please set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log", reload and let you project configure (or better, for more complete output, run "Clean configure" from the commands palette) and share with us the two files in .vscode subfolder: extension.log and dryrun.log.

One reason that is expected and not a bug is for when the output of a build is too cryptic. The extension needs to see a linker command to parse the launch target from the linker output. Or there could be a bug in the fact that the information is available in the make output (that's why we need to see your .vscode/dryrun.log) but we fail to parse it.

**Comment by coriolus** [comment] 2022-02-24 23:00
I have sent the mail with logs to makefiletools@microsoft.com.

**Comment by andreeis** [comment] 2022-02-25 08:46
@coriolus, in extension.log I see that we detect one launch target, which is exactly what I would expect by reading your dryrun.log.
Search for "Found the following 1 launch targets defined in the makefile". That binary should be accessible from the left side UI panel that we created for Makefile Tools, there is a "launch target" UI element that you can click and trigger a quickPick to show up, with all the launch targets that we find.
If you don't notice the icon for the left side panel (it's something with C/C++), run the command "Makefile: Focus on project outline" from the palette.

**Comment by coriolus** [comment] 2022-02-25 10:46
I'm not disputing that this launch target is detected, but that only happened after I have manually added the launch configuration to settings.json. The question is why wasn't that launch target detected automatically? If you think it would be of any use, I can reinstall the extension and repeat the process.

**Comment by andreeis** [comment] 2022-02-25 17:54
@coriolus, maybe when you checked and there were no launch targets you haven't configured before. Or configure failed.
If this happens again, we are interested in seeing the new log. It should miss the "found the following1 launch targets" text.
You can delete the launch configuration from .vscode/settings.json and reload your project. You should still be able to find one entry in the launch configurations quickPick.

**Comment by gcampbell-msft** [comment] 2023-10-23 14:03
Hi, @pmatkov, could you confirm if this issue has been resolved for you? 

If we don't hear from you, we plan to close this issue soon, but we wanted to make sure we check in with you, thanks.

**Comment by pmatkov** [comment] 2023-10-23 18:22
Hi,

Actually, I don't know if it's resolved because I didn't continue using makefile tools. But, in either case you can close this issue. 

Thanks

**Comment by Silicon42** [comment] 2023-11-29 01:13
Hi, @gcampbell-msft, I seem to have this issue too or at least one with similar symptoms so don't close the issue quite yet. I recently had the detection of the launch targets stop working, which is strange since it worked at one point while working on this same project and the Makefile barely changed since then. I've tried manually specifying the targets in ".vscode/settings.json" but that didn't allow me to select them either. I've attached a log and the Makefile I'm using.
[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/13494933/extension.log)
[Makefile.txt](https://github.com/microsoft/vscode-makefile-tools/files/13494940/Makefile.txt)
The Git for the project I'm working on is [here](https://github.com/Silicon42/HiveTag)

**Comment by douglaslassance** [comment] 2023-12-23 09:07
I cannot pick a launch target, it just uses the one I have set for build instead.

**Comment by rbmetcalf** [comment] 2024-01-14 18:29
I have the same problem and solved it only by adding the launch target by hand in settings.json.

**Comment by yuzujr** [comment] 2024-02-17 13:08
> I have the same problem and solved it only by adding the launch target by hand in settings.json.

Same thing happens to me,could you please tell me how to just add the launch target by hand in settings.json?
And my tools cant recognise build target too.

**Comment by rbmetcalf** [comment] 2024-02-19 09:01
I ended up going a different route.  In my settings.json I made different cmake tasks to create Makefiles with different targets.  Then you need to rerun the task to change targets.  Not the best solution perhaps.

{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "cmake Debug",
            "type": "shell",
            "options": {
                "cwd": "${workspaceFolder}/build"
            },
            "command": "cmake -DCMAKE_BUILD_TYPE=Debug ..",
            "group": "build"
        },
        {
            "label": "cmake Release",
            "type": "shell",
            "options": {
                "cwd": "${workspaceFolder}/build"
            },
            "command": "cmake -DCMAKE_BUILD_TYPE=Release  .. ",
            "group": "build"
        }
    ]
}

**Comment by gcampbell-msft** [comment] 2024-05-28 15:29
> Hi, @gcampbell-msft, I seem to have this issue too or at least one with similar symptoms so don't close the issue quite yet. I recently had the detection of the launch targets stop working, which is strange since it worked at one point while working on this same project and the Makefile barely changed since then. I've tried manually specifying the targets in ".vscode/settings.json" but that didn't allow me to select them either. I've attached a log and the Makefile I'm using. [extension.log](https://github.com/microsoft/vscode-makefile-tools/files/13494933/extension.log) [Makefile.txt](https://github.com/microsoft/vscode-makefile-tools/files/13494940/Makefile.txt) The Git for the project I'm working on is [here](https://github.com/Silicon42/HiveTag)

@Silicon42 If you have time, could you investigate what version of the extension may have had this problem start happening? Also, what OS are you operating on?

**Comment by gcampbell-msft** [comment] 2024-07-22 16:26
Also, for @yuzujr @douglaslassance @Silicon42, to help us be able to investigate this issue, could you send the information requested in this comment: https://github.com/microsoft/vscode-makefile-tools/issues/198#issuecomment-886432594.

@Silicon42 I attempted to reproduce your github repo, (I assume on Linux, because it didn't work on Windows), and when I look at the extensionLog, I see that we aren't parsing any launch targets.  
My initial thought from looking at your Makefile, it could be that our parsing doesn't handle the complixities that your Makefile has. Providing us with the requested info can help us investigate. Thanks!

**Comment by gcampbell-msft** [comment] 2024-07-22 16:50
Ah, @Silicon42 I believe I have found the issue. I think it might be due to some part of your Makefile? The issue is that every command that we see in the "Make.exe" invocation output has the -c flag. In our code, for gcc/clang we avoid parsing for output binaries when we see flags that we know will stop compilation short of creating a target. 

Please let me know if there is any other information (like the info requested in the last comment) or anything else that I can try to help you with. I will leave the issue open for now, but plan to close in the coming weeks if no further action is needed.

**Comment by gcampbell-msft** [comment] 2024-08-14 14:55
Closing this issue as mentioned from the last comment. If anyone is still facing issues, please create a new issue. Thanks!

**Closed by gcampbell-msft** 2024-08-14 14:55 UTC
Labels: bug, more info needed
