### ISSUE TITLE
Why does the Configuring: Generating dry-run output takes so long?

### ISSUE THREAD

**Issue by Sarah-Callies** [microsoft/vscode-makefile-tools#348] opened 2022-07-28 02:21 UTC
When I start my vscode , the makefile-tools would start to configuring the project, but it always takes too long time to wait, can I fix this problem?

**Comment by andreeis** [comment] 2022-08-04 22:14
@Sarah-Callies, when the configure phase takes too long, it's either because the project is very large or there is a bug in the extension or there are some known situations we can't support yet in the way the makefiles are written.

To start finding the root of the problem, please set "makefile.loggingLevel": "Debug" and "makefile.extensionLog":  ".vscode/extension.log" in your .vscode/settings.json, then reload, let it process 2 mins let's say... then share with us .vscode/dryrun.log and .vscode/extension.log.

**Comment by Rack1600** [comment] 2023-01-24 08:16
+1
I have a project with 1000's of files, and Preprocessing the dry-run goes on for many minutes (I waited 20+ before restarting VSCode)

**Comment by andreeis** [comment] 2023-01-25 23:18
@Rack1600, do you have lines like "------------------" in your dryrun log? We are working on fixing one hang scenario related to the regular expression engine not being able to deal with those strings.
Did the preprocessing phase ever finish for you?
If you can, please share the project or at least the dryrun.log.

**Comment by andreeis** [comment] 2023-01-25 23:23
@Rack1600 , also note that this work item is about the "generating dryrun" phase taking too long, not "preprocessing dryrun log". If this is the phase that is slow in your case as well, then you can make in your usual development terminal a full clean build of your entire project, save the output and pass it to the extension via "makefile.buildLog". This will skip over the calls to the "make" executable and the generation of dryrun.log phase. The extension will parse all it needs from the output you give (supposing it is verbose enough, make sure you don't use silencing directives). You would only need to refresh it when you have new files or when you change compiler switches that are relevant for IntelliSense (since we don't generate each time ourselves we may operate on out of date log).

If the slow phase in your case is indeed the preprocessing phase and not the generating dryrun phase, the same problem will happen even if you apply the above workaround. For that we need to see the dryrun.log to see what strings are in there causing trouble: "----------" or something else.

**Comment by Colengms** [comment] 2023-03-23 22:36
I repro an issue (possibly the same) using the https://github.com/python/cpython repo, on Ubuntu 22.04 via WSL2.  I waited maybe an hour before giving up on it.

While there is no Makefile Tools log output, I do see the following repeated over and over in the cpptools log output:  

```
LSP: cpptools/fileCreated: file:///home/colen/repos/cpython/conftest.err
LSP: cpptools/fileCreated: file:///home/colen/repos/cpython/conftest.o
LSP: cpptools/fileChanged: file:///home/colen/repos/cpython/confdefs.h
LSP: cpptools/fileChanged: file:///home/colen/repos/cpython/conftest.c
```
(etc.)

![image](https://user-images.githubusercontent.com/49173979/227379636-b5fe17b1-c560-41ae-9919-0d92461191c0.png)

This was also after I had run `./configure` and `make` in the repo, which took only a couple minutes total.

**Comment by andreeis** [comment] 2023-03-23 23:35
@Colengms , I confirm in your case the problem is not the "-----" string but simply the issue we always knew that some repositories cannot be built with "make --dry-run --always-make", which is the command we need to run at open project time. In theory this command doesn't do anything, only displays what would happen once we remove --dry-run. The --always-make we need so that we see all compile/link commands for source files even when up to date, so that we parse that information and generate IntelliSense configurations.
For some repositories (that I don't know what to recommend how to change the authoring of the makefiles) the combination of --dry-run with --always-make is causing the configure phase to run infinitely. This happens in terminal as well, outside of the extension and VSCode. It's just that no developer ever needs that combination.
One workaround is to remove --always-make from the array setting "makefile.dryrunSwitches". This will cause "make --dry-run" to not show compile/link commands for source files that are up to date. In order to see accurate IntelliSense, you must edit the source files. Once you do a real build (giving them the up to date status) you lose IntelliSense again.
Another workaround is to create a full clean most verbose log of the whole code base. Pass it via "makefile.buildLog" and you'll benefit of full features (will be also faster, no run of "make" under the covers). But it will slowly become stale. You need to refresh the build with any relevant changes: files add/remove, compiler/linker switches changes that impact IntelliSense.

**Comment by andreeis** [comment] 2023-03-27 19:11
@bobbrow , you are totally right... I forgot that the cache saves us from this doomsday scenario :).
So if one needs to remove --always-make (which is still preferred), the project needs a clean before being opened in VSCode, then configure will be complete without --always-make and saved in cache. Later, as long as the cache is not deleted, anything new will indeed be merged in.

**Closed** 2023-07-11 09:21 UTC
Labels: question, more info needed
